### ISSUE TITLE
Looking for a maintainer for the minikube addon

### ISSUE THREAD

**Issue by spowelljr** [headlamp-k8s/headlamp#1041]
Hi there, reaching out from the minikube project, thanks for integrating with our project! We would like to have a maintainer listed (GitHub username) for your headlamp addon. This would just be someone we can reach out to if say the addon is going to break with a new version of Kubernetes or a critical CVE is found in the image as we have little knowledge about the addon itself. Could you please find someone from the project that's willing to take this responsibility. Us reaching out will likely be extremely rare so it wouldn't be much or a burden. Going forward projects that don't have a maintainer might be at risk of being removed. Thanks!

**Comment by joaquimrocha** [comment]
@spowelljr , sorry I forgot to answer this after talking to Santhosh.
Santhosh is the maintainer for the addon. When he's not available please feel free to reach out to me.
