### ISSUE TITLE
Bugs after putting tabs to the top

### ISSUE THREAD

**Issue by lijianzhi01** [headlamp-k8s/headlamp#1087]
I am using following code to move customized tabs to top. But rest of sub tabs does not show up. 
```
registerSidebarEntryFilter(entry => {
  copSidebar.push({...entry, name: `cust-${entry.name}`});
  return entry.name.indexOf('cust-') == 0 || sidebarItems.map(item => item.name).includes(entry.name);
});

copSidebar.splice(0, 0, ...sidebarItems);
copSidebar.forEach(item => registerSidebarEntry(item));
```
I request **http://localhost:3000/c/mycluster**, but tab doesn't expand. 
![image](https://user-images.githubusercontent.com/13809749/232777383-0bb9d822-0e51-4a58-9196-1be2bc6307fe.png)

**Comment by joaquimrocha** [comment]
@lijianzhi01 , I think there was a work around for this, right? Should we close this issue?

**Comment by joaquimrocha** [comment]
@lijianzhi01 has confirmed this is fixed.
