### ISSUE TITLE
registerAppBarAction issue

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#1088]
There's an issue with this...

![issue-action](https://user-images.githubusercontent.com/9541/232829826-4b411f8d-8c57-42a5-bb74-17bb37d7a857.png)

Which is a problem with our use of redux, where often we are mutating state. Unfortunately because everything is all tangled together simply deep cloning all the state each time is a bit of a performance hit. Ultimately the fix would be to move this into a redux slice. But that's a more time consuming refactor. So, maybe doing a deep clone of state is enough for now.

**Comment by joaquimrocha** [comment]
Yeah, seems like the redux update uncovered all these issues. I also opened #1090 to handle another case.
I wonder if reverting that redux change for the release makes sense.

**Comment by illume** [comment]
@lijianzhi01 There's a fix in main for this now. Thanks @joaquimrocha and @vyncent-t
