### ISSUE TITLE
Backend html-static-dir doesn't work in Windows

### ISSUE THREAD

**Issue by lijianzhi01** [headlamp-k8s/headlamp#1094]
**Command**: headlamp_server.exe --dev=true --proxy-urls=* --html-static-dir=frontend/build
**Path generated in line 191**: C:\Users\***\Desktop\***\frontend\build\C:
**Error Message**: CreateFile C:\Users\***\Desktop\****\frontend\build\C:\index: The filename, directory name, or volume label syntax is incorrect.
![image](https://user-images.githubusercontent.com/13809749/233332437-d649b21b-28c9-46c7-b344-bb8beebdba80.png)
![image](https://user-images.githubusercontent.com/13809749/233332650-4e80d522-d521-42a4-b969-fb3489c3929e.png)

**Comment by illume** [comment]
I'll look into this one.

**Comment by lijianzhi01** [comment]
The page will be white if load static files from backend. I am using plugins as well.
How to reproduce:
1. build frontend
2. run backend: headlamp_server.exe --dev=true --proxy-urls=* --html-static-dir=../frontend/build
3. select a cluster it will be ok in cluster page 
4. refresh page, then page is white
![image](https://github.com/headlamp-k8s/headlamp/assets/13809749/c1f15092-5e11-42ae-adac-1196d23cc8db)
