### ISSUE TITLE
When I use baseUrl feature, plugins doesn't work

### ISSUE THREAD

**Issue by Rolika4** [headlamp-k8s/headlamp#1102]
**Description**

Use plugins in the headlamp when base-url option is enabled.

**Impact**

When the base-URL option is enabled - plugins don't draw in the Headlamp UI.

**Environment and steps to reproduce**

Set-up:
Kubernetes 1.23, nginx-ingress controller, Keycloak OIDC enabled
Headlamp in cluster deployed with settings:
1.    deployment:

          args:
            - '-in-cluster'
            - '-plugins-dir=/headlamp/plugins'
            - '-oidc-client-id=<client_id>'
            - '-oidc-client-secret=$(CLIENT_SECRET)'
            - >-
              -oidc-idp-issuer-url=https://<keycloak_url>/auth/realms/<headlamp_realm>
            - "-base-url=/headlamp"

2.   ingress:

          spec:
            rules:
              - host: >-
                 <dns_name>.com
                http:
                  paths:
                    - path: /headlamp
                      pathType: Prefix
                      backend:
                        service:
                          name: edp-headlamp
                          port:
                            number: 80

**Additional information**

I tried to copy plugins from the custom directory (/headlamp/plugins) to the Headlamp base plugins directory, but it did not help to resolve this issue. 

Attached 2 screenshots. 
Without base-URL features
![headlamp_work](https://user-images.githubusercontent.com/52344283/233966845-c36002e0-95b8-4e0c-a2cd-a1c36ec37e6b.png)
With base-URL features
![headlamp_un](https://user-images.githubusercontent.com/52344283/233966862-e1468a1e-1419-478d-809d-2993b56082ac.png)

**Comment by illume** [comment]
I'm pretty sure this works now.
