### ISSUE TITLE
Alternative methods to provide OIDC configuration

### ISSUE THREAD

**Issue by maxsargentdev** [headlamp-k8s/headlamp#1160]
Hi,

I have noticed that the only way to provide the OIDC configuration (which some of is sensitive) is directly in the values file.

It would be good to be able to support loading this configuration from environment variables or files. If you are using a GitOps approach for managing your deployment of headlamp the current setup forces you into bad practice.

Is this a welcome change? If so I will make it.

Thanks,
Max Sargent

**Comment by maxsargentdev** [comment]
I did not read enough of the source, I have found the HEADLAMP_CONFIG_ prefix now, thanks.

**Comment by maxsargentdev** [comment]
Re-opening, this change will now be a request for:

- Trivial change to the helm chart to support setting environment variables from a secret
- Updating the koanf usage so that it can read the settings from a flat yaml file mounted at a pre-specified location

Thanks.

**Comment by joaquimrocha** [comment]
Thanks @maxsargentdev . We will look into this.
