### ISSUE TITLE
OIDC login bug that require log in twice to success

### ISSUE THREAD

**Issue by Jaguar-Kwok** [headlamp-k8s/headlamp#1194]
I have noticed that users are required to log in twice via OIDC to successfully gain access. This could potentially be a bug that needs to be addressed to streamline the login process.

**Comment by jking916** [comment]
What I'm seeing is that after logging in the first time with OIDC, the user isn't redirected from `/c/main/login` to `/c/main`. When logging in a second time, it does redirect. But I also noticed that if I manually go to `/c/main` after the first login attempt, it works as expected. So this seems like an issue with redirection and not specifically with authentication.

**Comment by jking916** [comment]
Just noting that I saw this bug on version 0.18.0 and it's still there from my testing in version 0.19.0.

**Comment by zhekazuev** [comment]
Hello everyone,

I have the same problem on version `0.20.1`.
OIDC provider is Keycloak.

I'm using Keycloak like an OIDC provider for Kubernetes Dashboard and for Headlamp.
Users must log in twice through OIDC login button to successfully gain access.

Flow:
* go through https://headlamp.example.com
* redirected to `/c/main/login` page with authentication buttons - `sign in` or `token`
* choose sign-in
* login on the second page via keycloak
* keycloak page closed and I see page with authentication buttons
* tap `sign in` again
* redirected to `/c/main` sucessfully authenticated.

**Comment by bobbled** [comment]
> What I'm seeing is that after logging in the first time with OIDC, the user isn't redirected from `/c/main/login` to `/c/main`. When logging in a second time, it does redirect. But I also noticed that if I manually go to `/c/main` after the first login attempt, it works as expected. So this seems like an issue with redirection and not specifically with authentication.

Seeing the exact same issue with dex oidc using headlamp v0.22.0.  Going straight to /c/main after the first login lets me skip the second login.

**Comment by joaquimrocha** [comment]
@yolossn , Does the #1636 PR fix this one too?

**Comment by yolossn** [comment]
Nope this issue isn't solved by #1636. From the comments raised looks like the frontend is not picking up the token from the redirect in the first try. Ill take a look into this.

**Comment by yolossn** [comment]
@bobbled Is this issue happening every time you try to login or is it happening randomly? May I know which browser you are using? I tried testing the same using my setup and It seems to work in the first go for me. 

https://github.com/headlamp-k8s/headlamp/assets/22731013/4a2f0bef-33e4-4445-a582-1274fa327778

**Comment by illume** [comment]
@Jaguar-Kwok @zhekazuev @jking916 I wonder if you know if this "login twice required" issue is still happening?

**Comment by zhekazuev** [comment]
> @Jaguar-Kwok @zhekazuev @jking916 I wonder if you know if this "login twice required" issue is still happening?

Hi,

Checked right now.

Fixed in 0.23.0 Helm Version(0.24.1 appVersion).

**Comment by illume** [comment]
Thanks @zhekazuev
