### ISSUE TITLE
VPAs Missing in Configuration

### ISSUE THREAD

**Issue by thepaulmacca** [headlamp-k8s/headlamp#1305]
I've just come across this project and coming from Lens - I'm really liking it so far, thanks for the work you're putting into it! 👍

I'm not sure if this has already been noted (I've checked the other issues but haven't seen anything related), but I have a VPA deployed to one of my namespaces, and I don't see `VPAs` in the `Configuration` section

![image](https://github.com/headlamp-k8s/headlamp/assets/41340540/6ed84f24-be50-4806-ba2f-73b247291ecd)

Has anyone else noticed this?

**Comment by joaquimrocha** [comment]
Thanks @thepaulmacca . We will look into this.

**Comment by thepaulmacca** [comment]
@joaquimrocha are there any plans to have this added soon?

**Comment by joaquimrocha** [comment]
Yes. I took a brief look and it was trickier to test than I expected. Let's aim for 0.22.0 which should be in 1 month.

**Comment by thepaulmacca** [comment]
- @joaquimrocha thanks for the update, much appreciated. It'll be a great addition, as I imagine quite a few out there are using VPAs

This is a great tool, thanks for the work you and others put into it 👍🏻

**Comment by joaquimrocha** [comment]
@thepaulmacca Thank you. And if you spot more features that are missing, please do let us know! We want to make this the k8s UI for everyone.

**Comment by joaquimrocha** [comment]
@thepaulmacca VPAs are finally in a release (0.22.0) 😉 
Cheers!
