### ISSUE TITLE
Resource quota of cpu isn't right

### ISSUE THREAD

**Issue by lijianzhi01** [headlamp-k8s/headlamp#1306]
It should be quantity instead of zero.

<img width="1161" alt="image" src="https://github.com/headlamp-k8s/headlamp/assets/13809749/6df52354-7085-46c8-ba57-9b47d6abfa63">

https://github.com/headlamp-k8s/headlamp/blob/8a4ff8478ed13dff27e9152dfb3b836aedb3830e/frontend/src/lib/util.ts#L431

<img width="737" alt="image" src="https://github.com/headlamp-k8s/headlamp/assets/13809749/53ee26ac-3a92-4529-a986-5519e4d4fa6f">

**Comment by joaquimrocha** [comment]
Fixed in 0.19.1.
