### ISSUE TITLE
Spawn Job missing since 0.18.0

### ISSUE THREAD

**Issue by spasche** [headlamp-k8s/headlamp#1339]
Hi,

I noticed that the "Spawn Job" button available on CronJob resources is missing on releases after 0.17.1.

i.e., the button was visible on release 0.17.1:
![image](https://github.com/headlamp-k8s/headlamp/assets/105751/e579ac31-f675-4e65-8927-8f4d5dbc5385)

On both 0.18.0 and 0.19.0, I don't see the link.

**Comment by joaquimrocha** [comment]
I have just verified and you are right. It's missing and it's a bug. We'll try to include a fix in this week's bug fix release.
