### ISSUE TITLE
Failed to load module "xapp-gtk3-module"

### ISSUE THREAD

**Issue by O5ten** [headlamp-k8s/headlamp#1384]
### Problem:
Headlamp starts but with a white empty window. 

### Expected behavior: 
Some kind of interface to work with. I'm a firsttime user so i don't know what to expect. #:dango: 

### Console output:
```bash
$ flatpak run io.kinvolk.Headlamp
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (sv_SE.UTF-8)
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (sv_SE.UTF-8)
09:13:14.805 › App starting...
Check for updates:  true
Gtk-Message: 09:13:14.810: Failed to load module "xapp-gtk3-module"
[3:0907/091314.842813:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0907/091314.842838:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
(node:3) UnhandledPromiseRejectionWarning: /bin/sh: warning: setlocale: LC_ALL: cannot change locale (sv_SE.UTF-8)
(Use `headlamp --trace-warnings ...` to show where the warning was created)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

### OS:
**Linux mint 21.1 Vera** which is based on **Ubuntu 22.04.3 LTS**

### Package manager:
Flatpak

### Headlamp version
**0.19.1**

**Comment by joaquimrocha** [comment]
Hi @O5ten , I did try the 0.19.1 build on Ubuntu 22.04 and it worked.
I see an unhandled exception in the logs so that sounds related.
For helping me debug this, do you know if you're restricting any access of Headlamp to your home? (You can use the Flatseal app to check)
Maybe try moving out the ~/.kubeconfig and see if it loads. If it does, maybe it's a problem in reading the kubeconfig and that's something we really need to fix so I will ask you for more details if that's the case.

If you prefer a direct chat, we're on [K8s Slack](https://kubernetes.slack.com/messages/headlamp).

**Comment by illume** [comment]
We do have a lot of changes since this issue was reported... so maybe it's fixed now?

To try and reproduce this, someone would need to try "Linux mint 21.1 Vera" to see if it works. Since no one has been able to reproduce this on Ubuntu 22.04.

**Comment by illume** [comment]
I haven't been able to reproduce this issue, and don't have a way to debug it without help.

@O5ten I understand it's been a long time, but if you are interested in trying a few steps to try debug I'd appreciate it.

Steps to try:
- Try the new version of Headlamp (`flatpak update io.kinvolk.Headlamp`)
- Look at the developer console. View -> Select "Toggle developer tools" menu option -> Click "Console" tab -> copy any errors to this issue.
- See if it loads after temporarily moving ~/.kubeconfig somewhere else.
- Maybe check if Headlamp access is being restricted to home. (You can use the Flatseal app to check)

**Comment by O5ten** [comment]
This seems to work now. I'm having plenty of issues but this issue is not one of them. I'll report them as separate issues.
