### ISSUE TITLE
Blog Post: Plugin Settings Feature

### ISSUE THREAD

**Issue by vyncent-t** [headlamp-k8s/headlamp#1389]
Images

- ![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/ccbe4bb7-7a91-43d0-98f9-0286b73404c4)

- ![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/cc70d077-18b9-4903-a7cc-12601d7a0f33)

- ![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/b32ed71a-f3b3-463d-a8a7-b404637684b8)

- ![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/59468a85-ace4-41d2-81ec-efde7a71115c)

**Comment by joaquimrocha** [comment]
Thanks @vyncent-t : https://headlamp.dev/blog/2023/09/plugin-management-ui/
