### ISSUE TITLE
a11y: Support prefers-reduced-motion preference

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#1390]
Motion makes some people ill, distracts them, or makes their system unusably slow.

- [ ] Make Headlamp respect this OS/browser level preference.
- [ ] Add a headlamp setting for manual setting/override (on, off, browser/os preference)

See:

- [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [Responsive Design for Motion](https://webkit.org/blog/7551/responsive-design-for-motion/)
- Mui has not implemented it yet, see https://github.com/mui/material-ui/issues/16367
- one way on how to implement it for a mui app https://github.com/mui/material-ui/issues/16367#issuecomment-569829175

**Comment by vyncent-t** [comment]
This would be fixable through media queries
