### ISSUE TITLE
BUG: Double requests

### ISSUE THREAD

**Issue by callmevladik** [headlamp-k8s/headlamp#1398]
It seems like after latest headlamp update something related to requests went wrong, since requests are repeated.

![image](https://github.com/headlamp-k8s/headlamp/assets/42180137/591b89f9-d112-4be3-ba60-d70edad28591)

Steps to reproduce:
Go to any list page and open network tab(disable cache).

**Comment by joaquimrocha** [comment]
Thanks @callmevladik . We will investigate this.
