### ISSUE TITLE
Jobs spawned from a cronjob don't appear in the cronjob jobs table

### ISSUE THREAD

**Issue by spasche** [headlamp-k8s/headlamp#1399]
I noticed that when a job is manually spawned from a cronjob using the "Spawn job" button, its created job doesn't appear in the cronjob jobs table.

Tested with headlamp version 0.19.1 and a k3s cluster at version 1.27.5.

**Comment by joaquimrocha** [comment]
Yeah. Must be a bug (forgotten ref) in the YAML we generate for the Job. Thanks for reporting. We'll take a look.
