### ISSUE TITLE
RFC: Add settings for plugins

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#1405]
Plugins may have preferences the user should change, so we should add the ability for plugins to register these.
I think there are actually 2 categories of settings: preferences related to the plugin, and preferences related to a feature related to the plugin.

In terms of UX, we should definitely have a way to show particular the user that they are changing the settings of a certain plugin, and this should probably be a view under the Settings > Plugins area. But for the feature settings, even if it's related to a plugin, maybe these would be at the General Settings or cluster Settings level, because e.g. a plugin may provide a custom logo for clusters and be active/inactive per cluster, so maybe this setting should be in the Cluster Settings view. OTOH, a plugin may provide a new app menu depending on whether the app is running on Windows, Linux, Mac, and this should be in the General Settings rather than the plugin's settings.

**Comment by illume** [comment]
This is done in #1678
