### ISSUE TITLE
Missing container images for v0.2.0

### ISSUE THREAD

**Issue by milas** [headlamp-k8s/headlamp#1414]
I think the GitHub Action needs to be retried: https://github.com/headlamp-k8s/headlamp/actions/runs/6344117586/job/17233520187

There was an incident with Docker Hub Registry: https://www.dockerstatus.com/pages/incident/533c6539221ae15e3f000031/6515dbc89fabff05350ae18d

(Disclaimer: I work for Docker Inc but not on the Hub team)

**Comment by joaquimrocha** [comment]
@milas Indeed. I noticed it this morning too and I'm already fixing the issue. Thanks for reporting.

**Comment by joaquimrocha** [comment]
The image is now published.
