### ISSUE TITLE
Blank page for /c/main/storage/persistentvolumeclaims when no namespace is selected

### ISSUE THREAD

**Issue by calebcall** [headlamp-k8s/headlamp#1431]
When I try to view the persistent volume claims page when I don't have it filtered to at least one namepsace, I get a blank white page.  In the console, I get the below error

![Screenshot 2023-10-03 at 8 43 24 AM](https://github.com/headlamp-k8s/headlamp/assets/1132262/630146d8-9e19-46db-835e-835686752a61)

All other pages seem to work fine without any namespace filters (i.e. viewing all resources).

Headlamp Version: 0.19.1
Kubernetes Version: 1.27.5

**Comment by joaquimrocha** [comment]
Hi @calebcall . Thanks for reporting this issue. We'll look into it.
