### ISSUE TITLE
The Persistent Volume Claims page is not working

### ISSUE THREAD

**Issue by arcenik** [headlamp-k8s/headlamp#1444]
On the latest version (0.20.1) the PVC page is blank and headlamp has to be restarted.

On the console I can see the the following error.

```
apiProxy.ts:955 WebSocket connection to
'ws://localhost:4466/clusters/admin@talos-cluster/api/v1/persistentvolumeclaims?watch=1&resourceVersion=60924699' failed: WebSocket is closed before the connection is established.

apiProxy.ts:985 Error in api stream 
{err: Event, path: 'api/v1/persistentvolumeclaims?watch=1&resourceVersion=60924699'}
err: Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 0, …}
path: "api/v1/persistentvolumeclaims?watch=1&resourceVersion=60924699"
```

But I could not see any error on the backend side.

**Comment by vyncent-t** [comment]
I haven't been able to reproduce this locally, this may be related to some data in your persistent volume claim, could you try clearing the console to better source the issue?

**Comment by joaquimrocha** [comment]
@arcenik , Can you give us more details about the cluster you're using and whether you have access to all the namespaces there?
And this is when you go Storage > Persistent Volume Claims, right?

**Comment by joaquimrocha** [comment]
@arcenik , Thanks for the video. I don't think the backend logs would help here, but if you can share more logs from the frontend, maybe that will unblock it here. I really want to fix this for the next version.

**Comment by joaquimrocha** [comment]
Thanks for the info. I have added a PR that I hope fixes your issue ( #1474 ).
I have also built a [Linux ](https://github.com/headlamp-k8s/headlamp/actions/runs/6562594688)and [Windows ](https://github.com/headlamp-k8s/headlamp/suites/17365920017/artifacts/992414013)versions of Headlamp with this commit, in case you can test them and see if the issues does get fixed.

**Comment by arcenik** [comment]
Hi,

The test version is working, but in fact it got fixed before I installed it.

The token.name variable changed from 'name' to 'cluster' and data.cluster is defined.

Best regards

**Comment by joaquimrocha** [comment]
@arcenik , wait, I don't understand :) Do you mean the current release (0.20.1) doesn't have this issue after all?

**Comment by arcenik** [comment]
Hi @joaquimrocha 

I mean the condition to trigger the bug disappeared for unknown reason 

Before (see previous screenshot)
```
token = { name: 'name' ...
data = { name: undefined, cluster: 'admin@talos-zur1' }
```

And now
```
token = { name: 'cluster' ...
data = { cluster: 'admin@talos-zur1' }
```

![image](https://github.com/headlamp-k8s/headlamp/assets/1905755/d634979e-ff99-4421-aff9-b5514036f048)

**Comment by joaquimrocha** [comment]
I'm still skeptical that this has to do with the token. I'll probably merge the patch I got as a defensive approach...
