### ISSUE TITLE
Create an FAQ for Headlamp

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#1473]
There are many questions related to Headlamp that are common to those not familiar with the project.
We want to create an FAQ section in the docs and link it from relevant places.

**Acceptance Criteria**
- [x] We have an FAQ section in the docs
- [x] We have a link to the FAQ section in the README
- [x] We have a link to the FAQ section in the webpage's footer

**Comment by RISHIKESHk07** [comment]
Hey @joaquimrocha i would love to contribute , are the faqs already written or should I search for them , it's my first time contributing here would appreciate any guidance

**Comment by joaquimrocha** [comment]
We have some ideas but we definitely don't have them written down yet. Maybe a collaborative doc would be best, but a PR can also work. It'd be in the docs/ folder. We can move it to the right place if we don't get the location right the first time.

**Comment by joaquimrocha** [comment]
Just to be a bit more clear: we'd appreciate your contributions for sure. Check out the docs and let me know if you need more guidance.

**Comment by RISHIKESHk07** [comment]
@joaquimrocha could you please tell me where the footer is

**Comment by joaquimrocha** [comment]
> @joaquimrocha could you please tell me where the footer is

Hi @RISHIKESHk07 , sorry for the delay in replying. I was on vacation.
The footer in headlamp's website is configured in the conifg.yaml file (look for `footer` there)
