### ISSUE TITLE
RFC: Allow to download all logs instead of just the lines currently chosen

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#1481]
Right now the download button for the logs will include only the log lines that are currently selected. However, some users may want to download all the logs.

I think that if the user has chosen a number of lines and has a download button in the same context, it makes sense for the download to include those lines (i.e. download what's being shown). So I think we should offer both options: download X lines, download the full log, but this may be a bit confusing, so maybe just having that download be the full log is the best approach here.

**Comment by knrt10** [comment]
I am working on this.

**Comment by joaquimrocha** [comment]
@lijianzhi01 Please check out how we implemented this. Basically it's just another option for displaying all logs. And the download button should download all logs if that's the option selected.
