### ISSUE TITLE
Style Issue for Endpoints Field in Service View

### ISSUE THREAD

**Issue by vyncent-t** [headlamp-k8s/headlamp#1500]
# Style Issue for Endpoints Field in Service View

## Description
In the detailed view of a service, a styling issue is observed under the Endpoints section where the table renders a blank box across all viewing sizes. This issue hinders the user's ability to view and interact with endpoint information efficiently.

I will work on this bug if this blank rendering is not intended.

## Expected Behavior
- The table under the Endpoints section should render correctly and display the relevant information without any blank box or misalignment.

## Steps to Reproduce
1. Navigate to the Service View.
2. Select a service to view its details.
3. Scroll down to the Endpoints section to observe the blank box in the table rendering.

## Possible Solution
- Inspect the styling and rendering logic for the Endpoints section to identify and fix the source of the issue.

![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/017ba551-59f5-485e-9623-e0b7550df004)

**Comment by Src0p** [comment]
Can someone , review my PR  related to this issue https://github.com/headlamp-k8s/headlamp/pull/1510

**Comment by vyncent-t** [comment]
@Src0p 
Thank you for your contribution! I'll review your PR shortly.
