### ISSUE TITLE
Allowed pods number is not OK

### ISSUE THREAD

**Issue by metal3d** [headlamp-k8s/headlamp#1531]
The count of pods is OK but not the "allowed" - it seems that it only count for one node while the cluster has actually 3 nodes here

![image](https://github.com/headlamp-k8s/headlamp/assets/100080/f9b1e052-c341-419b-9c10-f18bbc303790)

This isn't the case for CPUs or Memory stats.

Sometimes, the counter is OK... I have no explanations for the reason this is not the rights stats.

**Comment by joaquimrocha** [comment]
@metal3d , you're saying the number shown in that chart is not all the pods you have in the cluster? What about the pods' list, does it show all pods?

**Comment by metal3d** [comment]
This is the number of pods in the cluster, not the chart. Pod list is sometimes not complete BTW.

**Comment by metal3d** [comment]
Hooo it's not the "allowed" pods number! Sorry, that's a bad habit to see this in Rancher and I misunderstood the value. It says that I've got 77 running pods for 77 asked.

**Comment by joaquimrocha** [comment]
That's fine.
If you have suggestions to improve Headlamp, especially given your experience with other tools, please share them with us.
