### ISSUE TITLE
Proposal: add handy buttons for deployments

### ISSUE THREAD

**Issue by razonyang** [headlamp-k8s/headlamp#1540]
It would be helpful that if provides these buttons like OpenLens.

![image](https://github.com/headlamp-k8s/headlamp/assets/17720932/64d991d7-d2c2-4d6a-9b56-6da6ca1e41e6)

**Comment by joaquimrocha** [comment]
@razonyang , yes, we have that in our plans!

**Comment by joaquimrocha** [comment]
Duplicate of #1006

**Comment by skoeva** [comment]
Fixed by #2044, closing this now
