### ISSUE TITLE
Missing Metrics Button in inCluster Deployment

### ISSUE THREAD

**Issue by SquupS** [headlamp-k8s/headlamp#1560]
Hi,

I was really looking forward to the funtionality, displaying Prometheus Metrics in Headlamp. I have now updated to the latest v0.21.0 in my cluster but I don't have the button mentioned on you docs. Speaking of that one

![image](https://github.com/headlamp-k8s/headlamp/assets/86827605/bbbe296b-8847-4982-a216-8063d22a9637)

Am I missing some config or is this only available in DesktopInstallation.

Thanks and again, great work

**Comment by joaquimrocha** [comment]
@SquupS , you're right. It's only available in the desktop version, but this plugin should also be in the official image. So we'll look into it and try to have it available in the web version for the next release.

**Comment by joaquimrocha** [comment]
BTW, adding plugins as a separate image should also not be complicated.
We have a guide on how to do that here: https://headlamp.dev/blog/2022/10/get-up-to-speed-deploying-headlamp-with-plugins/

**Comment by joaquimrocha** [comment]
This is now available in 0.22.0.

**Comment by mabrarov** [comment]
Hi @joaquimrocha,

Just FYI: metrics (at least CPU and memory consumption) of workloads is available in Kubernetes Dashboard with side container and when [Kubernetes Metrics Server](https://github.com/kubernetes-sigs/metrics-server) is deployed.

It looks like Headlamp also works with [Metrics API](https://github.com/kubernetes/metrics) (implemented by Metrics Server), but only for CPU and memory resources of compute nodes. I'm not sure if there is any existing / opened GitHub issue (feature request) for Headlamp to use Metrics API to show resources consumed by workloads (there are some issues which seem to be about the same).

My team considers Headlamp as replacement for Kubernetes Dashboard. So far everything looks good (and if something is missing then Headlamp team quickly adds / fixes that) - only some minor (rarely used) features are missing and lack of metrics of workloads is one of them (nice to see, but not required for real work).

Thank you.
