### ISSUE TITLE
eks cluster not working

### ISSUE THREAD

**Issue by sombriks** [headlamp-k8s/headlamp#1566]
i just installed headlamp from flatpak store

i created a locak k0s cluster and it's working ok

however, when i configure my eks cluster it fails to access it
![image](https://github.com/headlamp-k8s/headlamp/assets/556695/f9e2f62e-7a43-40c4-b17f-9fab4ac2c61a)

cluster was added with `aws eks update-kubeconfig`

Any guidance is welcome.

**Comment by knrt10** [comment]
Hey @sombriks I think this might be an issue with the `kubeconfig`. `Not found` for cluster is generally when the server that headlamp is trying to access is inaccessible. Are you able to access the eks cluster via `kubectl` command line?

**Comment by sombriks** [comment]
Hello @knrt10 !

Yes i was, kubectl for this works.

my better guess is the fact i was trying to use headlamp from flatpak; i did the in-cluster installation and everything worked as expected.

i don't have that environment available right now but i will try non-flatpak desktop version and see if it works.

**Comment by joaquimrocha** [comment]
@sombriks , if your kubeconfig's user needs to run an external command for the authentication, that's something headlamp doesn support. See #1582.

**Comment by sombriks** [comment]
> @sombriks , if your kubeconfig's user needs to run an external command for the authentication, that's something headlamp doesn support. See #1582.

Yes, that was exactly my scenario!

Thankfully in-cluster headlamp is working like a charm!
