### ISSUE TITLE
JWT is not refreshed after it expires

### ISSUE THREAD

**Issue by CrimsonFez** [headlamp-k8s/headlamp#1587]
Hello,
I have setup headlamp with keycloak for oidc.
The issue I'm having is that after 5 minutes (my token lifespan) headlamp isn't authenticated anymore.
The ability for headlamp to get a new token with the refresh token should be added.

I don't understand the inner workings of headlamp, but maybe you could use `oidc-ts` to handle oidc tokens.

**Comment by joaquimrocha** [comment]
cc/ @yolossn
