### ISSUE TITLE
Verify why common/index.test.ts is not checking all files in common/

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#1597]
I just realized from #1596 that the common/index.test.ts doesn't check all the files (if it did, that PR would have failed).
So we need to verify why it's not checking all files.

**Comment by vyncent-t** [comment]
- when running tests there is a folder 'auth verify', which isnt included in test.ts (test.ts checks every file to determine if it is to be exported)
- test.ts (catches files that are unintendedly added, stills runs even though there are files that are not tracked by the tests

to run:
- write `cd frontend`
- run `npm run test` 
- press `p`
- choose common folder
