### ISSUE TITLE
Add settings view

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#16]
There should be a settings view to allow the user to configre several aspects of the dashboard / clusters.

**Acceptance Criteria:**
- [ ] There is a settings button and view available
- [ ] At first, the settings should allow to see the details of all the clusters configured and change their accent color (#15)

Design:

TBD

**Comment by ashu8912** [comment]
@joaquimrocha is there a design ready for this

**Comment by joaquimrocha** [comment]
Not yet.

**Comment by joaquimrocha** [comment]
The design is close to finish.

**Comment by joaquimrocha** [comment]
I had added a mockup here but turns out it needs some final touch.

**Comment by illume** [comment]
With github settings, I like how each section has it's own URL. So when you click on the sides or link to the settings from documentation or another part of the app it works.

What I *don't* like about github settings is you can't easily link to a section. Often there are many sections on a page, so you need to scroll down a lot. For example, if you click on the "Appearance" sidebar menu, and scroll down you see "Emoji skin tone preference". Would be better if there was an anchor on that section so people could link to it.

<img width="897" alt="image" src="https://user-images.githubusercontent.com/9541/196168430-7ae7085e-ecd4-4d06-b373-952fd4c61982.png">

**Comment by yolossn** [comment]
I think we can take "inspiration" from vscode for the way it handles settings for plugins, it allows plugins to have their own settings in a separate subsection.

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/22731013/196402923-547fe7a5-91aa-4eb7-a853-b14fc038471c.png">

**Comment by joaquimrocha** [comment]
Here is the latest design we have from @tsompura:
![Settings design image](https://user-images.githubusercontent.com/1029635/196447057-0eb04228-a858-4523-8dc3-00b47223dd92.png)

Also, about the search, I think it makes sense when we have more than a few options, i.e. more than one "page" of settings. This will likely happen in the future, but as an MVP for settings, I don't think search is needed.

**Comment by ashu8912** [comment]
<img width="1194" alt="Screenshot 2022-12-23 at 12 44 02 PM" src="https://user-images.githubusercontent.com/30126128/209289814-27ea68da-202d-4db9-b6c6-f9aef0d1049d.png">

**Comment by yolossn** [comment]
Adding the points from our discussion.
1. In In-cluster mode it is import to make the message correct that the settings are specific to the user and not something a admin can set for the whole application. Like setting the language to french for example and expecting it to be the default for all users.
2. In In-cluster mode if the user sets the settings in a browser and accesses headlamp from another device or browser the settings will be completely different.
