### ISSUE TITLE
configuration (server port)

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#160]
**Current situation**

Currently the server process port is hard coded. Perhaps people will want to use another one.

Configuration of other things may be needed.

**Impact**

Some people won't be able to run Headlamp if it's not configured for their environment.

Each configuration increases the size of the testing matrix.

**Ideal future situation**

People can configure Headlamp so they are comfy.

**Implementation options**

There's already some command line options (for headless mode).

How could they configure this (and other things)?

- environment variables
- command line
- configure in the app (for people not using the command line)
- a configuration file (perhaps writable by the app but not when hosted)
- Headlamp can run in different ways: app, hosted, headless

**Comment by knrt10** [comment]
User can now configure [port](https://github.com/headlamp-k8s/headlamp/blob/main/backend/pkg/config/config.go#L28) in headlamp. So, closing this.
