### ISSUE TITLE
RFC: Multi delete

### ISSUE THREAD

**Issue by farodin91** [headlamp-k8s/headlamp#1604]
Add a way delete multi resources at same time.

Impl Idea: use table selection and than https://mui.com/material-ui/react-table/#data-table and action items to the resource view, for example delete or restart.

**Comment by joaquimrocha** [comment]
We want to have batch actions in the table but I was thinking we should use an advanced table for this, like  https://www.material-react-table.com/

**Comment by illume** [comment]
We have the new table now... so I guess we can revisit this now?

**Comment by joaquimrocha** [comment]
Awesome. Thanks!
