### ISSUE TITLE
frontend: sidebar order workflow improvements

### ISSUE THREAD

**Issue by farodin91** [headlamp-k8s/headlamp#1613]
Sidebar Storage:
Change the order from StorageClass,PV,PVC to PVC,PV,SC

Sidebar Configuration:
![image](https://github.com/headlamp-k8s/headlamp/assets/1159212/dd24d2da-27f2-4849-84b7-b135ecdc58f2)

What does anyone think?

**Comment by joaquimrocha** [comment]
Thanks @farodin91 . Can you explain the motivation for the change?

**Comment by farodin91** [comment]
For Storage, i think is use frequency. Also if you click on storage, pvcs are show which probably, more helpful for the most users than storageclasses.

For Config, I moved limit range and resource quotas together as they are used together, same for priority class and runtime class.
