### ISSUE TITLE
Load Valid Contexts from Kubeconfig Despite Errors

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#1628]
In the testing for the latest release I have noticed that Headlamp was not loading any of the clusters in Mac and Windows (somehow in WSL it worked, maybe because the kubeconfig is different or because I didn't test correctly).

So we ended up having to revert the related commit: https://github.com/headlamp-k8s/headlamp/pull/1627

We need to check what is wrong in that code. I will share my (sanitized) kubeconfig privately.

**Comment by knrt10** [comment]
Adding more information on this, currently the Headlamp returns no context even if there is one error with kubeconfig. As discussed with the team it is concluded we should not renter Headlamp useless if there if only 1 issue in multi cluster setup.

We should show working clusters which are valid in Kubeconfig

**Comment by knrt10** [comment]
Started work on this.

**Comment by illume** [comment]
No one got to this yet, so moving to next release milestone.
