### ISSUE TITLE
Show the origin of each cluster in the home view

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#1632]
In the home view, we should have a new column in the clusters list called _origin_ which shows the user whether the clusters are coming from a kubeconfig (and which path), in-cluster, or dynamic (if we could have the plugin name here or a string identifying who added it'd be great).

**Comment by knrt10** [comment]
Working on this

**Comment by knrt10** [comment]
This issue needs design, removing myself right now
