### ISSUE TITLE
Enable Pod filter by node name and pod status

### ISSUE THREAD

**Issue by lijianzhi01** [headlamp-k8s/headlamp#1641]
In Pod list page, we want to filter pods by node name or pod status.

**Comment by achauve** [comment]
@joaquimrocha I can't find how to add new filters using a plugin. Is it possible or is it planned? or the only solution is to add the feature in headlamp directly?

**Comment by joaquimrocha** [comment]
Hi @achauve , you are rights we need to add more advanced filters. We have a plan for doing that before #1646 (this one will allow filter by any column) and be configurable by each table. Maybe in 3 weeks.

**Comment by joaquimrocha** [comment]
I believe this is already done after we added the new table. Please confirm @lijianzhi01 .
