### ISSUE TITLE
Missing exit full screen in Air Gapped cloud

### ISSUE THREAD

**Issue by lijianzhi01** [headlamp-k8s/headlamp#1644]
It seems like exit full screen icon isn't cached properly. 

![image](https://github.com/headlamp-k8s/headlamp/assets/13809749/bcbe5a43-8828-47bf-9c86-0c83d7119297)

**Comment by illume** [comment]
We have a test for icons. The PR was here: https://github.com/headlamp-k8s/headlamp/pull/1277
