### ISSUE TITLE
Option to rename a cluster?

### ISSUE THREAD

**Issue by waldner** [headlamp-k8s/headlamp#1653]
Sometimes it would be useful to be able to assign a custom name to an imported cluster (for example, because it's the same or too similar to an existing one). It seems to me that currently headlamp just takes the name it finds in the kubeconfig and that cannot be changed afterwards.

**Comment by joaquimrocha** [comment]
Yup. We should have that. I will add it to the backlog.

**Comment by knrt10** [comment]
Working on this.

**Comment by joaquimrocha** [comment]
I think the UI needs a bit of tweaking.
This is how it looked before:
![Error before](https://github.com/headlamp-k8s/headlamp/assets/1029635/f2dc7504-1193-466c-98e5-13d4f395866b)

This is after my patch:
![Error after](https://github.com/headlamp-k8s/headlamp/assets/1029635/997d7681-275e-4ac9-8002-502ff5ea2565)

Also, I added that restriction of only showing the UI if in electron, which was missing.

However, trying the logic again I see an issue: it renames but still is using the old name at some point.
![Error while authenticating to a renamed cluster](https://github.com/headlamp-k8s/headlamp/assets/1029635/b704a364-60b3-4a6c-96f0-6d9a864fb79c)

Renaming back to what it was originally also didn't work (didn't do the renaming back).

So I think this feature still needs some work and therefore it will be added for the next milestone.
