### ISSUE TITLE
Mobile: Sidebar elements and Navigation tabs not visible

### ISSUE THREAD

**Issue by tazo90** [headlamp-k8s/headlamp#1719]
Currently on mobile devices, the elements in the sidebar and navigation tabs are not visible, limiting users' access to navigation.

### Problem 1: Sidebar elements not visible

![sidebar-before](https://github.com/headlamp-k8s/headlamp/assets/3165572/55596288-2ff5-44b4-9ac8-2e80196be268)

---

### Problem 2: Invisible Navigation Tabs

![navigation-tabs-before](https://github.com/headlamp-k8s/headlamp/assets/3165572/4cc61b7f-eb55-483f-86a4-8ef36d1ce730)

**Comment by tracetechnical** [comment]
Facing this issue on mobile too, trying to move to this from Kubenav, but sadly its not usable as it is for mobile :(

**Comment by tracetechnical** [comment]
Seeing this on a Galaxy S21

Browser mode:
![Screenshot_20240328_233003_Brave.jpg](https://github.com/headlamp-k8s/headlamp/assets/22156780/c7989a2f-c07b-4d37-8782-deb282bf56bf)

PWA mode:
![Screenshot_20240328_233015_Brave.jpg](https://github.com/headlamp-k8s/headlamp/assets/22156780/6c47c655-cc3e-4031-ae94-5fcc6e469a2e)
