### ISSUE TITLE
Replace minikube with k3d when testing in CI

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#1746]
We use minikube for testing changes in-cluster in CI, but minikube can take some time, which means PR checks take longer than they should.

So we should replace minikube by a lighter k8s flavor (except in places where we're actually deliberately testing for minikube functionality). This page shows that to be k3d: https://minikube.sigs.k8s.io/docs/benchmarks/timetok8s/v1.32.0/

**Comment by joaquimrocha** [comment]
Following the discussion in the team, please check how much the _minikube_ step alone is taking in order to verify whether this issue is required.

**Comment by skoeva** [comment]
> Following the discussion in the team, please check how much the _minikube_ step alone is taking in order to verify whether this issue is required.

See the "Build Container and test" runs in the Actions tab, using minikube the "start cluster" step takes around 1m30s with minikube, while the runs in CI using k3d are 1min quicker:
![image](https://github.com/headlamp-k8s/headlamp/assets/52797224/d374be2a-0ffb-40af-9b91-b441a7729b8b)
![image](https://github.com/headlamp-k8s/headlamp/assets/52797224/c5f9da1f-f114-4800-92f6-720f7240c5dd)
