### ISSUE TITLE
Plugins are not disabling correctly

### ISSUE THREAD

**Issue by knrt10** [headlamp-k8s/headlamp#1760]
### Setup

- Run headlamp in-cluster or locally.
- Go to plugin settings http://localhost:3000/settings/plugins
- Click on toggle button to disable plugins

### Expected behaviour

Plugin should be disabled

### Actual behaviour

Plugin still works

### Screenshot

<img width="1506" alt="Screenshot 2024-03-03 at 8 56 30 PM" src="https://github.com/headlamp-k8s/headlamp/assets/24803604/4e7c14e9-f907-40ed-801f-ceeabae2983d">

cc @yolossn

**Comment by yolossn** [comment]
When the `Save and Apply` button is clicked after enabling/disabling a plugin the values is getting changed in localStorage and redux as expected. Looks like an existing issue cc: @vyncent-t @illume

**Comment by yolossn** [comment]
When the `Save and Apply` button is clicked after enabling/disabling a plugin the values is getting changed in localStorage and redux as expected. But still the plugin is loading, looks like a pre existing issue cc: @vyncent-t @illume

**Comment by illume** [comment]
Plugins should only be able to be disabled in app mode. Not in-cluster. The UI should not be available out of app mode, so I'll fix that.

I confirmed it works in app mode.

**Comment by illume** [comment]
Added a fix in https://github.com/headlamp-k8s/headlamp/pull/1570
