### ISSUE TITLE
Init containers always show status as "Error" when in terminated state

### ISSUE THREAD

**Issue by jda258** [headlamp-k8s/headlamp#1778]
There probably needs to be a conditional that only sets the state to error if the return code is not 0.

https://github.com/headlamp-k8s/headlamp/blob/7d25e012ea6f5dacde0a8ad746ea2d9349eec674/frontend/src/components/common/Resource/Resource.tsx#L679

**Comment by illume** [comment]
This was fixed May 29 in this PR:
- #2000

```ts
      } else if (!!state.terminated) {
        stateDetails = state.terminated;
        if (state.terminated.exitCode === 0) {
          statusType = '';
          label = state.terminated.reason;
        } else {
          statusType = 'error';
          label = t('translation|Error');
        }
      }
```
