### ISSUE TITLE
frontend: No spacing on these tags on conditions in deployments

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#1789]
The condition tags are visually joint, so they should have a small gap separating them:

![Screenshot showing the tags joint visually](https://github.com/headlamp-k8s/headlamp/assets/1029635/8ba0791d-0ea2-4858-8c6b-97c1cdf4c5a3)

## Notes

- See headlamp/frontend/src/components/common/Label.tsx, the StatusLabel function, and where it's used.
- See the [general development guide](https://headlamp.dev/docs/latest/development/)
- See the [frontend contributing guide](https://headlamp.dev/docs/latest/development/frontend/) in docs/development/frontend.md
- You will need to run `make run-frontend` and `make run-backend` in separate terminals
- `cd frontend && npm install` to install everything to run the frontend
- It uses TypeScript, React, Mui for components, and react router for links.

**Comment by vyncent-t** [comment]
This issue is not seen on the current main

**Comment by vyncent-t** [comment]
this can be closed maybe?

**Comment by vyncent-t** [comment]
![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/41a8b280-bdb7-4714-b685-324eb05058ad)

**Comment by illume** [comment]
> This issue is not seen on the current main

Cool.
