### ISSUE TITLE
frontend: Cluster view: Ordering of items within workloads is not consistent

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#1791]
The workloads have a corresponding chart for each subentry in the sidebar (Deployments, DaemonSets, Pods...). But those charts aren't shown in the same order as the sidebar.

Use the ordering from the sidebar to order the charts.

![Screenshot showing the discrepancy between charts + sidebar in the workloads](https://github.com/headlamp-k8s/headlamp/assets/9541/c749482e-ab6a-4630-b9ac-afe1464f6fac)

- See the [general development guide](https://headlamp.dev/docs/latest/development/)
- See the [frontend contributing guide](https://headlamp.dev/docs/latest/development/frontend/) in docs/development/frontend.md
- You will need to run `make run-frontend` and `make run-backend` in separate terminals
- `cd frontend && npm install` to install everything to run the frontend
- `npm run storybook` can be used to develop the component separately without needing to set up kubernetes or the backend.
- See the frontend/src/components/workloads/ folder especially Overview.tsx

**Comment by illume** [comment]
This was fixed by @r0b2g1t in #1852
