### ISSUE TITLE
frontend: Make Workloads overview circular chart's names clickable

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#1792]
As an extra way of accessing the workloads corresponding to each chart, we should make sure that the workloads' circular charts' names are clickable (taking the user to the corresponding workload list page).

## Notes

- See the [general development guide](https://headlamp.dev/docs/latest/development/)
- See the [frontend contributing guide](https://headlamp.dev/docs/latest/development/frontend/) in docs/development/frontend.md
- You will need to run `make run-frontend` and `make run-backend` in separate terminals
- `cd frontend && npm install` to install everything to run the frontend
- `npm run storybook` can be used to develop the component separately without needing to set up kubernetes or the backend.
- See the frontend/src/components/workloads/ folder especially Overview.tsx
- It uses TypeScript, React, Mui for components, and react router for links.

---

Make these charts clickable:

![image](https://github.com/headlamp-k8s/headlamp/assets/9541/18a18d23-94b0-4d5e-bf22-0ff5f11f54b6)

**Comment by illume** [comment]
This was done by @vyncent-t in #2021
