### ISSUE TITLE
backend: Refactor release.go UpgradeRelease to be shorter

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#1793]
This function needs to be shorter to reduce the complexity of it, and make it easier to understand.

Currently the code turns off the linter for this issue with "//nolint:funlen".

- [ ] refactor the code to make the function short and easier to understand
- See quick start contributing guide on how to get started.
- See [headlamp/backend/pkg/helm/release.go](https://github.com/headlamp-k8s/headlamp/blob/main/backend/pkg/helm/release.go#L628) file.
- See [backend contributing guide](https://headlamp.dev/docs/latest/development/backend/)
- To run the linter, `make backend-lint`
- How to run tests: `make backend-test`

<br><br>
---

Related umbrella backend refactoring clean up issue https://github.com/headlamp-k8s/headlamp/issues/855 (other pieces of code have the linter disabled and could also be fixed up, feel free to refactor a different function.)

**Comment by HariCharan-001** [comment]
I'd like to work on this !
You can assign it to me.

**Comment by HariCharan-001** [comment]
Hi, 
I've submitted a PR.
Ensured consistency in coding/ naming conventions.
