### ISSUE TITLE
Loading kubeconfig seems broken

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#1831]
_Originally posted by @gaalw in https://github.com/headlamp-k8s/headlamp/issues/389#issuecomment-2008874569_

Steps to reproduce.

```brew install --cask headlamp
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 5 taps (hashicorp/tap, weaveworks/tap, minio/stable, homebrew/core and homebrew/cask).
==> New Formulae
cotp                 git-split-diffs      hashicorp/tap/hcp    tartufo              whisperkit-cli       yo
==> New Casks
nperf                           posture-pal                     proton-mail                     steinberg-activation-manager

You have 79 outdated formulae and 3 outdated casks installed.

==> Downloading https://github.com/kinvolk/headlamp/releases/download/v0.23.0/Headlamp-0.23.0-mac-x64.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/220546758/eb639fc6-b9ab-4da6-bb
########################################################################################################################## 100.0%
==> Installing Cask headlamp
==> Moving App 'Headlamp.app' to '/Applications/Headlamp.app'
```

Run Headlamp.

<img width="1786" alt="Screenshot 2024-03-20 at 08 02 06" src="https://github.com/headlamp-k8s/headlamp/assets/103998526/f581307e-e9ad-44d5-b155-747fcea0d26f">

The clusters from `~/.kube/config` are loaded properly.

If I click on "Load kubeconfig" button:

<img width="744" alt="Screenshot 2024-03-20 at 08 02 47" src="https://github.com/headlamp-k8s/headlamp/assets/103998526/1aa77e5d-4622-4b0f-a423-ab88b1fc0c79">

<img width="704" alt="Screenshot 2024-03-20 at 08 03 04" src="https://github.com/headlamp-k8s/headlamp/assets/103998526/bfb3b970-1eb2-4444-849a-c8e7e65fee24">

<img width="674" alt="Screenshot 2024-03-20 at 08 03 11" src="https://github.com/headlamp-k8s/headlamp/assets/103998526/c8a21d60-49b9-4d0c-818a-586fb759e5d5">

So the function of loading external kubeconfig is not working at all. No idea why.

**Comment by pgollangi** [comment]
I see same issue with latest headlamp

**Comment by creidmiller** [comment]
In case it is of any help, I was able to workaround this issue by adding additional entries to kubeconfig for our Azure K8s clusters by appending the --admin parameter as in this example:

az aks get-credentials -g QAKubeRB -n QAKube --admin

The original cluster entries added to kubconfig without --admin are not accessible but the new --admin entries work okay.  It's a bit awkward with 2 entries for each cluster:

![image](https://github.com/headlamp-k8s/headlamp/assets/9829670/264fff17-bc67-4606-b2fb-37bf15d62688)
