### ISSUE TITLE
e2e-tests: Add live update end to end test

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#1836]
Headlamp does live updates, but we don't have an end to end test that covers this yet.

- Add an end to end test. See [e2e-tests/](https://github.com/headlamp-k8s/headlamp/tree/main/e2e-tests) folder and the README in there on how to get started writing a test.

### The test

- in 1st browser context) authenticate
- in 2nd browser context) authenticate
- in 1st browser context) create a pod with a unique name
- in 2nd browser context) see pods page to see if it exists (should exist pretty quick, but up to 6 seconds)
- in 1st browser context) remove the pod
- in 2nd browser context) see pods page to see if it exists (should exist pretty quick, but up to 6 seconds)

### Notes 

- See the multiple context playwright feature in the documentation: https://playwright.dev/docs/browser-contexts#multiple-contexts-in-a-single-test
- See [e2e-tests/](https://github.com/headlamp-k8s/headlamp/tree/main/e2e-tests) folder

**Comment by knrt10** [comment]
Removing myself since @vyncent-t created a PR for it. To avoid confusion next time, can you please comment on the issue that you are working or assign it to yourself. Thanks

**Comment by illume** [comment]
Sorry about that @knrt10 its on me too, Vincent and I were looking into it the other week and I forgot to check the assignment. Will remember to do that in the future.
