### ISSUE TITLE
(WIP) Maximum depth error in chrome inspection

### ISSUE THREAD

**Issue by vyncent-t** [headlamp-k8s/headlamp#1853]
Not sure if this is already being worked on but will open an issue for it

## Description
While using the inspection tool there is a maximum depth error that continuously rolls regardless of what view is currently open.

I think it may be related to the notifications bit here, I have first noticed it after clearing local storage while working on a detail drawer branch feature.

![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/2f3eb44f-2a26-44f0-b2de-455d9788ca94)

## Steps to follow
- nav to any view on the current main and watch the inspection tool for about a minute

## Screenshot

![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/dd484f84-96ff-420d-a188-b3d9da8789dd)

**Comment by illume** [comment]
This old issue doesn't apply anymore.
