### ISSUE TITLE
Create OpenCost plugin

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#1860]
An [OpenCost](https://github.com/opencost/opencost) plugin would be a great addition to Headlamp as we could add more info to the multi-cluster table, and is a very valuable addition for many of our users.

I know OpenCost exports to prometheus, so maybe we could also add something to the prometheus plugin (for displaying a new tab with the cost).

**Comment by illume** [comment]
There's work ongoing for this in the plugins repo in this PR https://github.com/headlamp-k8s/plugins/pull/40

**Comment by illume** [comment]
This PR https://github.com/headlamp-k8s/plugins/pull/40 has been merged.

What else is to be done?

I see the README needs updating with relevant text, and also some screenshots added.

**Comment by joaquimrocha** [comment]
Yes. This is done after the PR I just merged.
