### ISSUE TITLE
Flathub Release is Unverified

### ISSUE THREAD

**Issue by harmathy** [headlamp-k8s/headlamp#1887]
Currently, the [flathub page of headlamp][1] shows an unverified badge:

![headlamp](https://github.com/headlamp-k8s/headlamp/assets/776348/04d8b8a6-e070-4d8a-8c30-fbee7ad32dd4)

If I understand #110 correctly, the flathub release is in fact *official*. Therefore, it would be nice to have the release verified.

[1]: https://flathub.org/apps/io.kinvolk.Headlamp

**Comment by illume** [comment]
Hello.

Thanks for letting us know. We will look into it.

Hrmmm… I don’t recall seeing it before, so I wonder if it’s a new thing.

cheers,

**Comment by harmathy** [comment]
Here is the documentation about verification: <https://docs.flathub.org/docs/for-app-authors/verification>

**Comment by joaquimrocha** [comment]
I have added the verification. Thanks for raising this, @harmathy . I will also handle other app quality items that can be improved, from what flathub's dev panel tells me.
If there are other things we need to do to improve the flatpak experience, do let us know!
