### ISSUE TITLE
Helm chart - give an option to pass additional command line arguments

### ISSUE THREAD

**Issue by gecube** [headlamp-k8s/headlamp#1898]
Hi!

As an user I want to pass an additional command line arguments to the headlamp deployment. Now there is no such an option.

Particularly I am interested in `-insecure-ssl` command line option for debug purposes

Alternative: make all command line options to have an ENV variable alternative and allow user to pass them to the deployment.

**Comment by knrt10** [comment]
working on it

**Comment by gecube** [comment]
@knrt10 thanks for the update.
