### ISSUE TITLE
Make headlamp-plugin faster

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#1899]
headlamp-plugin checks whether there are updates to it every time we run it. While this is nice and useful in a normal use, if we run the command repeatedly, this feature does impact dev experience by taking a long time when we may just be running a simple command, as every check takes usually 1.5-2.0 sec .

So I suggest we only check for updates a limited number of times per day. Maybe once a day is even enough.

If the update is to be skipped, we could print a message telling the user how to force check the updates.

cc/ @illume

**Comment by illume** [comment]
Are you having this issue in just the `npm start` command?

That should usually be only run once, and then the command just sits there watching for changes - with no update check done. I understand it would be more of a problem when the `npm start` was buggy and it had to be run on each change.

**Comment by joaquimrocha** [comment]
During the "watch" bug it was certainly annoying. But also in live demos it usually just seems like it takes too long.
I think it's worth making faster or only running sporadically, but certainly not urgent.
