### ISSUE TITLE
npx playwright test command errors

### ISSUE THREAD

**Issue by vyncent-t** [headlamp-k8s/headlamp#1914]
Running the command `npx playwright test` to run the set of test at the same time causes some errors to occur. I think there are some issues that may depend on a different env, I will work on those that are immediately fixable.

### How to reproduce
- follow instructions under e2e-tests README.md
- cd into e2e-tests dir
- use `npx playwright test`

fixed:
create a namespace with the minimal editor then delete it

ERRORS LIST

progress: 0/3

- [ ] There is cluster choose button and main cluster is selected
- [ ] Store modified kubeconfig to IndexDB and check if present
- [ ] check test is present in cluster and working

![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/ce3f48e3-c9f1-4c19-9c51-6120257811b0)

progress: 0/3

- [ ] plugin settings page should have a title
- [ ] plugin settings page should have a table
- [ ] pod counter plugin should have setting option

![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/39307182-24a8-43f9-8c7a-552926039bc4)

progress: 0/2

- [ ] GET /plugins/list returns plugins list
- [ ] Service account tab should have headlamp-admin

![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/289ef10a-72e1-4452-92a9-c54fac3139a1)

progress: 1/1
- [x]  FIXED: create a namespace with the minimal editor then delete it
![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/61a8aaf4-36d4-4459-9912-3060e1e1eddc)

**Comment by joaquimrocha** [comment]
Closing in favor of #1963 .
