### ISSUE TITLE
Desktop-App: Clicking on hostname in ingress opens URL in the app

### ISSUE THREAD

**Issue by micw** [headlamp-k8s/headlamp#1917]
I'm using the desktop app (installed on arch linux with aur package). When I klick on the domain name in any ingress, it open's in the system browser as well as in the desktop app. I need to restart the desktop app after the click to get back to headlamp UI.

**Comment by joaquimrocha** [comment]
This used to happen somewhere else as well and I thought we had fixed it completely but apparently not. Thanks for reporting. We will check it out.
