### ISSUE TITLE
charts: Add a values schema

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#1926]
It was mentioned here https://github.com/headlamp-k8s/headlamp/issues/1897 to take a look at the bitnami charts for postgresql.

The have some docs  https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml#L1635
Also they have a values.schema.json https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.schema.json

So this issue is about adding a values.schema.json JSON schema file.
https://helm.sh/docs/topics/charts/#schema-files
https://medium.com/@hans.knechtions/6-tips-to-writing-a-great-helm-chart-35899b00a6cc

This would help people use the headlamp chart, by validating the user input.

---

Additionally, on artifact hub one of the quality badges is missing because it does not use a values schema.

![image](https://github.com/headlamp-k8s/headlamp/assets/9541/f28c3f53-70ea-4609-bc2b-181181cee6ab)

**Comment by knrt10** [comment]
Thank you for creating the issue. Working on this

**Comment by engnatha** [comment]
Adding this schema reduced some flexibility that was previously useful. Things like https://github.com/kubernetes-sigs/headlamp/issues/2022#issuecomment-2143334793 are no longer supported. This was useful to avoid having to specify all the details for oidc configuration in an external secret. Most of the items that go into configuring OIDC aren't actual secrets.

**Comment by knrt10** [comment]
Thank you for pointing it out. Will try to figure out how we can avoid it and have the same flexibility as before
