### ISSUE TITLE
Settings are a bit confusing

### ISSUE THREAD

**Issue by sniok** [headlamp-k8s/headlamp#1927]
Currently the settings icon in the top right corner just says "Settings". For example I was looking for the theme toggle and assumed it would be there but it was actually cluster settings. Then to get the headlamp settings you need to click "General settings" which is even more confusing because what is "general" about it?

Maybe we can put cluster settings in the sidebar on the left? Next to all the existing cluster stuff. Then in the navbar we can have headlamp settings, all the way in the corner unrelated to the cluster.

![image](https://github.com/headlamp-k8s/headlamp/assets/4517681/803ebb85-9aad-46c7-8560-f920aeaa487e)

**Comment by joaquimrocha** [comment]
I have avoided adding settings there because it would show right below Configuration. So you would have Configuration + Settings, which sounds just confusing.
I will bring this question to the design team so we they can probably give a final suggestion.
