### ISSUE TITLE
Plugins endlessly reloading on dev only app

### ISSUE THREAD

**Issue by skoeva** [headlamp-k8s/headlamp#1937]
running `npm run dev-only-app` locally with the `.plugins` directory in headlamp causes a loop of checks for updates to the plugins. deleting this directory fixes the issue though.
![Screenshot 2024-04-29 111907](https://github.com/headlamp-k8s/headlamp/assets/52797224/2e1a6195-b49c-4223-964c-0f3b2ca46037)
![image](https://github.com/headlamp-k8s/headlamp/assets/52797224/3581440d-368b-46c4-9f7d-7d0d97359908)

**Comment by joaquimrocha** [comment]
I don't think we need to watch for changes in the static-plugins folder, so we should just remove that from the watch list.
