### ISSUE TITLE
Option to pass Cluster Settings via Config for user Groups

### ISSUE THREAD

**Issue by derbauer97** [headlamp-k8s/headlamp#1962]
Hello! We're delighted users of Headlamp!

Our objective is to provide users with the capability to view their Resource Status and Definitions without necessitating the development of a custom UI. It's important to note that our users possess restricted access limited to their respective Namespace.

We've been actively utilizing Custom Resources, and to facilitate their access via Headlamp while maintaining restricted permissions, we need to configure the namespace within the cluster settings under allowed Namespaces otherwise if not possible it would be greate to have an option to filter namespaces in the CustomResource Overview like it is possible with Workloads.

I found this issue which i can confirm is fixed and described a similar problem: https://github.com/headlamp-k8s/headlamp/issues/1553

**Comment by joaquimrocha** [comment]
> Hello! We're delighted users of Headlamp!

Nice! Happy to meet you!

> Our objective is to provide users with the capability to view their Resource Status and Definitions without necessitating the development of a custom UI. It's important to note that our users possess restricted access limited to their respective Namespace.

Just slightly related, but we are improving how users get aware that they need to configure the list of "allowed" namespaces if they don't have permissions to list all namespaces.

> We've been actively utilizing Custom Resources, and to facilitate their access via Headlamp while maintaining restricted permissions, we need to configure the namespace within the cluster settings under allowed Namespaces otherwise if not possible it would be greate to have an option to filter namespaces in the CustomResource Overview like it is possible with Workloads.

Yeah. I think that makes sense. We will get to it.

> I found this issue which i can confirm is fixed and described a similar problem: #1553

Thank you. I will close it.

**Comment by Guilamb** [comment]
so I've made a pull request that adds a new page that displays the CRs and enables Namespace filtering, in order to maintain the namespace flow as in the workloads.

I hope this helps. If you have any suggestions or improvements, please feel free to mention me or send me a message on Slack. 😄
