### ISSUE TITLE
headlamp helm chart should be signed

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#1989]
Artifact hub is complaining that the helm chart is not signed.

![image](https://github.com/headlamp-k8s/headlamp/assets/9541/60d81527-e443-47bc-abf2-dc3b84f03b6e)

Note: there's an issue for all of our releases being signed here: https://github.com/headlamp-k8s/headlamp/issues/2092

---

From the [helm documentation](https://helm.sh/docs/helm/helm_package/#helm-package)
> To sign a chart, use the '--sign' flag. In most cases, you should also provide '--keyring path/to/secret/keys' and '--key keyname'.
> 
> $ helm package --sign ./mychart --key mykey --keyring ~/.gnupg/secring.gpg
> 
> If '--keyring' is not specified, Helm usually defaults to the public keyring unless your environment is otherwise configured.

**Comment by knrt10** [comment]
Working on this
