### ISSUE TITLE
Clicking Save & Apply in Plugin page opens browser

### ISSUE THREAD

**Issue by sniok** [headlamp-k8s/headlamp#1990]
Expected:
When I click on Save & Apply it should apply plugins (disabled/enabled state)

Actual: 
It opens a web browser and doesn't apply plugins

![image](https://github.com/headlamp-k8s/headlamp/assets/4517681/d9364a5e-f950-4d0a-899c-9fbaae446932)

**Comment by joaquimrocha** [comment]
I notice this today just by opening the app on Mac. Not sure what's going on. Perhaps it has to do with those changes we did to not open URLs externally. (Though this is the opposite)
