### ISSUE TITLE
Websocket Connections resuliting in Forbidden

### ISSUE THREAD

**Issue by rowan-vr** [headlamp-k8s/headlamp#2023]
I've been working with Headlamp for quite a while now however, I never had a working websocket connection. I first figured out that the host was not added to the cors for `kube-apiserver`, however after adding that the issue persisted.

The verbose kube-apiserver logs show
```
I0602 17:59:03.237196       1 authorization.go:87] "Forbidden" URI="/api/v1/namespaces?watch=1&resourceVersion=4560559" reason=""
```
for all requests coming from Headlamp.

When trying to make the request using CURL the following is returned:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "pods \"kube-apiserver-master.rph\" is forbidden: User \"system:anonymous\" cannot watch resource \"pods\" in API group \"\" in the namespace \"kube-system\"",
  "reason": "Forbidden",
  "details": {
    "name": "kube-apiserver-master.rph",
    "kind": "pods"
  },
  "code": 403
}
```

However when directly opening the websocket to the kube-apiserver the websocket does connect.

I assume that it is an issue in the nginx configuration, but after hours of trail-and-error I have not been able to figure anything out. This is the configuration being used by nginx-ingress
```
# configuration for kube-system/headlamp
upstream kube-system-headlamp-k8s.roleplayhub.dev-rph-k8s-headlamp-80 {zone kube-system-headlamp-k8s.roleplayhub.dev-rph-k8s-headlamp-80 256k;
	random two least_conn;
	server 192.168.44.55:4466 max_fails=1 fail_timeout=10s max_conns=0;
}



server {
	listen 80;listen [::]:80;
	listen 443 ssl;listen [::]:443 ssl;
	ssl_certificate $secret_dir_path/kube-system-headlamp;
	ssl_certificate_key $secret_dir_path/kube-system-headlamp;

	server_tokens on;

	server_name k8s.roleplayhub.dev;

	set $resource_type "ingress";
	set $resource_name "headlamp";
	set $resource_namespace "kube-system";
	if ($scheme = http) {
		return 301 https://$host:443$request_uri;
	}
	large_client_header_buffers 4 64k;
	
	location / {
		set $service "rph-k8s-headlamp";
		proxy_http_version 1.1;

		proxy_connect_timeout 60s;
		proxy_read_timeout 60s;
		proxy_send_timeout 60s;
		client_max_body_size 1m;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering on;
		proxy_pass http://kube-system-headlamp-k8s.roleplayhub.dev-rph-k8s-headlamp-80;

		
	}
	
}
```

Any ideas on how to resolve this or debug the issue any further? I love headlamp and would love to see websockets in action as well!

**Comment by joaquimrocha** [comment]
Thanks for reporting @rowan-vr . Do you happen to have an idea what was the last Headlamp version that worked for you? That would help us look in the right direction.

**Comment by rowan-vr** [comment]
Hi, I've solved the problems!

It was because some default config settings from nginx-ingress-controller (https://docs.nginx.com/nginx-ingress-controller/) (NOT THE SAME AS nginx-ingress) were preventing websocket connections. 

To make it work using nginx-ingress-controller you have to enable the following flags in the ingress resource annotations:
```yaml
   nginx.org/proxy-buffering: "false"
   nginx.org/websocket-services: "headlamp"
```

**Comment by illume** [comment]
Oh right. We should try and add some better docs for this… or maybe we can detect the error and make a suggestion of how to fix it.
