### ISSUE TITLE
Delete a CRD doesn't work

### ISSUE THREAD

**Issue by Guilamb** [headlamp-k8s/headlamp#2028]
## Description: 
When attempting to remove a CRD, a green pop-up appears indicating that the CRD has been successfully deleted. However, upon further inspection, the CRD is still present in the cluster. This inconsistency between the UI feedback and the actual state of the system can lead to confusion.

## Steps to Reproduce:

    Navigate to the CRD section in the Kubernetes dashboard.
    Select a CRD to delete.
    Confirm deletion when prompted.

## Expected Behavior: 
The CRD should be completely removed.

## Actual Behavior: 
The UI indicates that the CRD has been deleted with a green pop-up message, but the CRD remains.
![crd_deletion_headlamp](https://github.com/headlamp-k8s/headlamp/assets/18172904/4ba1242c-cc85-40fa-a37b-5a471a1c093b)

**Comment by Guilamb** [comment]
If further information is required, please let me know. I am currently working on the main branch and running Headlamp in development mode using the commands make run-frontend and make run-backend.

Also the actions done in the Gif are : 
   - Creation of a CRD.
   - Attempt to delete the newly created CRD via the Headlamp interface.
   - Verification using kubectl to check if the CRD is still present in the cluster.
   - Deletion of the CRD using kubectl.
   - Confirmation that the CRD has been removed from Headlamp's CRD page.

**Comment by joaquimrocha** [comment]
Hi @Guilamb , which version of Headlamp was this on? Because I did fix an issue exactly like this in the last release.

**Comment by Guilamb** [comment]
Sorry, my bad, I was using commits from May 28th. After updating my branch the issue was resolved. Thank you for your assistance. I am closing this issue.

**Comment by joaquimrocha** [comment]
No worries. I'm glad it works now.
