### ISSUE TITLE
Network page failure (v0.24.0)

### ISSUE THREAD

**Issue by xianwum** [headlamp-k8s/headlamp#2046]
I installed Headlamp (0.24.0) on Windows 10 using the installer from
https://github.com/headlamp-k8s/headlamp/releases/download/v0.24.0/Headlamp-0.24.0-win-x64.exe

When testing a remote cluster (Openshift Container Platform 4.13), and accessing Network page, the Headlamp page error occurs with an error "Uh-oh! Something went wrong."

See the attached screenshot and logs for details.
![network_page_fails](https://github.com/headlamp-k8s/headlamp/assets/3334912/09e4bc42-b989-4b63-886f-dd08a8281085)
[Network_page_fails.txt](https://github.com/user-attachments/files/15879129/Network_page_fails.txt)

Notes:
I failed to reproduce the issue when testing remote clusters (kind v0.22.0 go1.20.13 linux/amd64) and accessing Network page with the Headlamp.

**Comment by joaquimrocha** [comment]
Maybe related: https://github.com/headlamp-k8s/headlamp/issues/2027

**Comment by joaquimrocha** [comment]
Fix is out in today's release.
