### ISSUE TITLE
Some UI regressions

### ISSUE THREAD

**Issue by sniok** [headlamp-k8s/headlamp#2049]
Here are some UI regressions I've noticed

- [ ] Menu labels are uppercase
![image](https://github.com/headlamp-k8s/headlamp/assets/4517681/39533fbe-223e-4381-96e5-ddd133a23331)

- [ ] Logs view has large padding
![image](https://github.com/headlamp-k8s/headlamp/assets/4517681/eea48f66-cfc3-4a9b-ab8f-e69be00e4398)

**Comment by vyncent-t** [comment]
some additional weird UI issues from the app mode

Cluster, Network, and Security on side bar
![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/79b18796-5cf2-4dca-a56a-d7624654c52c)

Top right icons
![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/b3db9fe1-4273-44e4-92fa-2ea5661bf468)

Calendar Icons
![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/7a02b7c6-6059-4f53-9472-a0aa36f55988)

* not easily screen capped but load the overview page and watch the circles load in
![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/ab687e5b-d402-4c9f-996a-66df2c54b06f)

**Comment by sniok** [comment]
White border in SimpleTable with dark theme 
![image](https://github.com/headlamp-k8s/headlamp/assets/4517681/47c08c33-b969-4f4c-8666-08e6a7baa760)
