### ISSUE TITLE
Provide option to create namespace

### ISSUE THREAD

**Issue by ChillarAnand** [headlamp-k8s/headlamp#2055]
When installing helm charts, I need to create a namespace on the fly many times.

Right now, in namespaces there is no option to create a namespace. This forces me to use kubectl just for creating namespace. It would be great if there is an option to create namespace directly.

<img width="1280" alt="Screenshot 2024-06-19 at 06 50 56" src="https://github.com/headlamp-k8s/headlamp/assets/4463796/109b1acd-f19b-4761-a16a-f67971faa1af">

**Comment by joaquimrocha** [comment]
Thanks. We have a PR opened about this. We should merge it very very soon.
