### ISSUE TITLE
Helm Charts page is broken

### ISSUE THREAD

**Issue by ChillarAnand** [headlamp-k8s/headlamp#2058]
I tried 0.24.0 & master branch build (by running make app-mac). Both seem to be crashing after opening any helm chart.

<img width="1280" alt="Screenshot 2024-06-20 at 06 59 26" src="https://github.com/headlamp-k8s/headlamp/assets/4463796/9738670a-0a17-4b8e-a02a-df96108ff032">

**Comment by joaquimrocha** [comment]
@ChillarAnand Thanks! Just to be sure. Can you confirm you have no headlamp-server already running when running the app?
@ashu8912 Can you test in your machine?

**Comment by ChillarAnand** [comment]
@joaquimrocha  I don't think headlamp-server is already running.

Before starting app:

<img width="1280" alt="Screenshot 2024-06-20 at 14 54 58" src="https://github.com/headlamp-k8s/headlamp/assets/4463796/87bd3510-2520-469f-a764-af8d9149d523">

When charts page has crashed:
<img width="1280" alt="Screenshot 2024-06-20 at 14 54 44" src="https://github.com/headlamp-k8s/headlamp/assets/4463796/e18ab3b0-045d-4bb2-814d-1781a1160019">

**Comment by ashu8912** [comment]
Hii @ChillarAnand  thanks for reporting this, can you check what's the output for `ps -ef | grep headlamp` for the dmg you downloaded from the releases, Does it have the application server running??

**Comment by ChillarAnand** [comment]
With the stable release, I am getting an error, when opening a chart.

ps:
<img width="1278" alt="Screenshot 2024-06-21 at 19 09 33" src="https://github.com/headlamp-k8s/headlamp/assets/4463796/e6e76162-cd22-470a-a725-00d65e748f59">

chart:
<img width="1278" alt="Screenshot 2024-06-21 at 19 10 50" src="https://github.com/headlamp-k8s/headlamp/assets/4463796/bfe4e273-3204-4910-8fed-15cec1f25613">

**Comment by sniok** [comment]
I can also reproduce it on the 0.24

It seems that response from the artifacthub has a bunch of gibberish at the end of the response

Here's the end of the body of the following request `https://artifacthub.io/api/v1/packages/d5dad873-8e69-411b-8391-933d4391988a/25.22.0/values`

![image](https://github.com/headlamp-k8s/headlamp/assets/4517681/4481117e-7aa6-41ab-a136-59b0b209468a)

Could it be an issue on their side?

**Comment by ChillarAnand** [comment]
I am seeing those characters on all the charts.

![Uploading Screenshot 2024-06-21 at 19.32.08.png…]()

**Comment by ChillarAnand** [comment]
Thank you, @sniok
