### ISSUE TITLE
Home link in "uh-oh" page doesn't work in app mode

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#2109]
When in the desktop app, if the "Uh-oh" page is shown, the "Get back home" link doesn't work. On Mac it reportedly tries to open the link in Finder, and on WSL it does nothing (likely tries to open the link but fails).

This means that users hitting this problem cannot navigate away from this page.

Let's do two things:
- [ ] Fix home link in app
- [ ] Add an app menu to navigate home
- [ ] Add back/forward app menus to navigate history

**Comment by joaquimrocha** [comment]
@ashu8912 , also please verify if this is happening on main only, or also in the latest v0.24.1 release.

**Comment by ashu8912** [comment]
This happens on v0.24.1 as well
