### ISSUE TITLE
chart: Image pull secrets not usable anymore

### ISSUE THREAD

**Issue by disconn3ct** [headlamp-k8s/headlamp#2113]
The [values schema](https://github.com/headlamp-k8s/headlamp/blame/df4efdd6252d39d9d7afac818f7274acfbc070a9/charts/headlamp/values.schema.json#L34) conflicts with the [k8s docs](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret) about image pull secrets.

Specifically, the chart now requires it to be an array of strings, which is still passed directly to 'toyaml'. K8S actually wants an array of secretref objects (`name`) in that slot.

Chart validates this:
```yaml
imagePullSecrets:
  - image-pull-secret
```
K8S wants this:
```yaml
imagePullSecrets:
  - name: image-pull-secret
```

**Comment by knrt10** [comment]
Thank you for opening the issue, will fix it
