### ISSUE TITLE
AuthVisible authenticates with any auth verb

### ISSUE THREAD

**Issue by skoeva** [headlamp-k8s/headlamp#2147]
Running into a bug where the AuthVisible component runs `getAuthorization` with an invalid authVerb and still returns an allowed status of true. Added some helpful screenshots.

### Setting the authVerb:
![image](https://github.com/headlamp-k8s/headlamp/assets/52797224/7d4d1f4d-bdad-4cfc-83bd-703baa0022f1)
### Logging within authVisible:
![image](https://github.com/headlamp-k8s/headlamp/assets/52797224/6e805e94-fa27-4e7b-a8b7-f47d4355e8a9)
### Log output:
![image](https://github.com/headlamp-k8s/headlamp/assets/52797224/f5cfc7f8-49f6-4e12-9b32-28d847ed0120)

**Comment by illume** [comment]
Are you able to leave instructions on how to reproduce this?
