### ISSUE TITLE
Release popup "Read more" not working

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#2171]
I have tried the "New release available" popup's _Read More_ button and it didn't open any URL. Didn't seem to do anything.
So we should look into it (after someone confirms this issue; I tested on WSL).

**Comment by illume** [comment]
It works for me in WSL, but I have a browser installed in there.

**Comment by joaquimrocha** [comment]
I think this is happening with all links from the app (at least in dev mode) in WSL.

**Comment by joaquimrocha** [comment]
And I don't have a browser installed in WSL but this was working before.

**Comment by illume** [comment]
I tried with Headlamp-0.24.1-linux-x64.AppImage and it opens my WSL chrome browser as well. So I don't believe it's a regression.

@joaquimrocha are you able to confirm 0.24.1 also doesn't work for you?

**Comment by illume** [comment]
Moving this to the next release milestone, as I'm pretty sure it's not a regression.

**Comment by joaquimrocha** [comment]
Opening PRs directly from the gh command in WSL has also stopped working. This is not a bug in Headlamp, as you correctly guessed @illume . Closing.
