### ISSUE TITLE
Headlamp 0.24.1 not available on WinGet

### ISSUE THREAD

**Issue by busches** [headlamp-k8s/headlamp#2188]
The latest release on WinGet is 0.24.0. As soon as you install and open Headlamp, you get a notification that an update is available.

**Comment by joaquimrocha** [comment]
Hmm. Maybe it failed without us realizing. Thank you for reporting, we will take a look.

**Comment by joaquimrocha** [comment]
Once this is merged, it should be available. Thanks @busches !
https://github.com/microsoft/winget-pkgs/pull/164117

**Comment by joaquimrocha** [comment]
This is done now.

**Comment by scottbusche-usps** [comment]
FYI this is happening again `0.28.0`, the latest is only `0.27.0`
