### ISSUE TITLE
Fix winget manifest generation

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#2191]
Seems like we need to update the winget script to use the schema 1.6 since the 1.5 are getting [rejected](https://github.com/microsoft/winget-pkgs/pull/164117#issuecomment-2243993894).
We should probably use [komac](https://github.com/russellbanks/Komac) for it.

**Comment by illume** [comment]
@vyncent-t I did a PR for this here: https://github.com/headlamp-k8s/headlamp/pull/2192
