### ISSUE TITLE
frontend not updating when plugins change, when opencost plugin installed

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#2196]
Currently in main the frontend is not updating when a change is made in a plugin, when the opencost plugin is installed.

Note: ideally no plugin should be able to stop the other ones loading when in development... so this should ultimately be fixed in the frontend/.

### impact

The impact is the developer experience is severely reduced. But only if the opencost plugin is installed.

### How to reproduce

- Install the opencost plugin.
- Notice that changes to plugins (other plugins) don't update the frontend/ or app when things are changed.

**Comment by illume** [comment]
Installing the opencost plugin causes it to stop working.

I don't think it's a regression. I had the same broken behaviour with an earlier version of Headlamp 0.24.1.

**Comment by sniok** [comment]
I can't seem to reproduce it. I installed opencost plugin, then npm start of kompose plugin and app is reloaded on every change in the kompose plugin. (0.24.1 and 0.25 rc)

**Comment by illume** [comment]
Thanks for testing it @sniok 

I wonder how you installed the opencost plugin? I installed it with `npm start` from the plugins repo main branch.

**Comment by sniok** [comment]
I tried installing it both from plugin catalog and from npm start. Same outcome

**Comment by illume** [comment]
Probably we should not block the release on this issue. Because the impact won't be so large. Only those making plugins who also install opencost plugin will be affected (and not everyone even then).

**Comment by joaquimrocha** [comment]
cc/ @vyncent-t

**Comment by joaquimrocha** [comment]
New tip: We need to review the hooks, after testing the latest version. cc/ @knrt10

**Comment by knrt10** [comment]
I tried with the latest main hash `e4b30811cf3d9f8079ed04adfc2beaf3ae4877a3` and it seems to work now. I installed opencost using `npm i && npm start`. Then I created nginx pod and see if frontend changed. It worked. I also installed change logo plugin and it seems to worked. Made changes to change-logo plugin, it also worked as well.

**Comment by vyncent-t** [comment]
It works for me with the open cost and app catalog running

**Comment by vyncent-t** [comment]
is this issue still remaining open if the latest main works? @illume
