### ISSUE TITLE
app catalog: "oops" page installing app in compiled app

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#2202]
When installing an app in the compiled app image, installing an app fails.

<img src="https://github.com/user-attachments/assets/65fbb4cb-b59b-4dc0-a87c-75b6f4f0bfcf" width=320>

minikube
ubuntu 22.04 WSL
make app-linux
./app/dist/Headlamp-0.24.0-linux-x86_64.AppImage

### How to reproduce

- Run compiled app (make with `make app-linux` for example and run that)
- Click install cluster
- Click Apps sidebar
- Search for prometheus
- Click install on the official prometheus app.

![image](https://github.com/user-attachments/assets/b2fe6238-6d65-450a-9275-f72f95b1492d)

Here's the traceback.

![image](https://github.com/user-attachments/assets/614e171f-0a50-4b6c-b3d2-118ee53f14bc)

It appears to crash just as the monaco editor is about to pop up.

### investigations so far

- 0fc5ff8e (before backend updates) does not work for me
- went further back to 2a5c4ab5 and the app doesn't load at all
- running with `npm start` shows a different error (this issue is not about that)

**Comment by joaquimrocha** [comment]
I have tried these instructions and couldn't get it to crash, both with the app built in the unpacked mode and from the CI.

**Comment by illume** [comment]
It's working now. Was picking up some old files in the build.
