### ISSUE TITLE
Mac ARM version shows 'developer not verified' message

### ISSUE THREAD

**Issue by questionmark78** [headlamp-k8s/headlamp#2221]
When installing/ updating to the 0.25.0 version, the app does not start because the developer can't be verified.

<img width="251" alt="Screenshot 2024-07-31 at 08 59 46" src="https://github.com/user-attachments/assets/3abc4dd1-3323-4371-a68f-7d3f487fbf18">

**Comment by joaquimrocha** [comment]
Weird. Didn't notice anything in the CI. I will check it out.

**Comment by joaquimrocha** [comment]
Should fixed now. Thanks for reporting @questionmark78 !
