### ISSUE TITLE
"Something went wrong" alert needs some work

### ISSUE THREAD

**Issue by sniok** [headlamp-k8s/headlamp#2314]
Tested on 0.25.1, disabled the network and this is how it looks like 

On wide screens it's way too short
![image](https://github.com/user-attachments/assets/e2384e9c-b64a-412f-acfb-19dfc3c93ecc)

Medium screens, covers the logo
![image](https://github.com/user-attachments/assets/41d3ec84-dbb0-4720-adb5-ff68b4cf5da7)

On narrow screens, padding pushes the content all the way to the right
![image](https://github.com/user-attachments/assets/a446d3a7-aefe-4df7-9a66-f1181a93f210)
![image](https://github.com/user-attachments/assets/1ef47ae5-42b9-47a0-8e44-984fadb6abcf)

This seems like a good component to use 

https://mui.com/material-ui/react-alert/

**Comment by sniok** [comment]
Also I think the message should be "Lost connection to the cluster" because it checks if the browser is online or if healthz endpoint of a cluster responds.

**Comment by skoeva** [comment]
+1 this banner has been really buggy and the message isn't at all visibly traceable to the issue

**Comment by skoeva** [comment]
Got around to checking out the alert component, looks promising. We can keep the width at 100% as before, but I think it would be cleaner and more convenient if the alert was a bit smaller (maybe something closer to this):

![image](https://github.com/user-attachments/assets/f571841a-f0b4-40e2-9904-931185660e40)

@sniok WDYT?
