### ISSUE TITLE
Opens index.html on startup when 3 or more plugins are installed

### ISSUE THREAD

**Issue by lsascha** [headlamp-k8s/headlamp#2320]
Opens `file:///D:/Program%20Files/Headlamp/resources/frontend/index.html` in the default browser when starting the app and 3 or more plugins are installed.

I tried to enable and disable random plugins, but every time i have at least 3 Plugins enabled, it opens the website.

Also opens the Website every time i press on "Save & Apply" in the Plugins Setting window.

- Headlamp Version: 0.25.1 Git Commit: 89e2c595c4e3f9c8034488d8ed7e91ef215f1cdb
- Operating System: Windows 11

![image](https://github.com/user-attachments/assets/6c7a4da1-c076-47c5-bb2f-9808bd79d94d)

**Comment by skoeva** [comment]
Hi, are you still noticing this issue?

**Comment by lsascha** [comment]
Hi. I just updated to test it. Seems like it is fixed. :)
Thank you.
