### ISSUE TITLE
Crash parsing nodes

### ISSUE THREAD

**Issue by Smana** [headlamp-k8s/headlamp#2339]
Hey everyone,

I installed Headlamp using my repo [here](https://github.com/Smana/cloud-native-ref/tree/main/tooling/base/headlamp).
When I try to open Headlamp I get the following error:

![Screenshot from 2024-09-18 09-08-19](https://github.com/user-attachments/assets/306db2b4-cc7d-4d3e-af70-74bb7ff25b48)

version: 0.25.0
eks: 1.30.4
plugins: kyverno,flux,change-logo,prometheus

Seems to be related to the nodes but I'm not sure, please let me know if I can give you more details.
Thank you!

**Comment by joaquimrocha** [comment]
@Smana Thanks. And sorry for the delay in answering.
Can you try with version 0.25.1? If it persists, we will definitely take a look.

**Comment by Smana** [comment]
I wasn't able to reproduce recently. Closing
