### ISSUE TITLE
Workloads -> Jobs menu fails when you have Jobs with more than one completion

### ISSUE THREAD

**Issue by tsipo** [headlamp-k8s/headlamp#2389]
I have followed the first example [here](https://medium.com/@muppedaanvesh/a-hand-on-guide-to-kubernetes-jobs-%EF%B8%8F-aa2edbb061ea ) to create a job with multiple completions (just create the job from [here](https://gist.github.com/anveshmuppeda/74c6d5c947faf31fe3289839c4590943/raw/0361ad41ca35540025b074858f75a972f315d31d/non-parallel-job.yaml) in some namespace).
If I then try to go to the Workloads -> Jobs menu item I get this:
![image](https://github.com/user-attachments/assets/2c58b499-9435-46be-bbb4-8585c633f743)
(and also clicking the home link doesn't go anywhere).
BTW If I find the job directly under Workloads and click it, I can see it fine:
![image](https://github.com/user-attachments/assets/471a1d4e-44ac-4286-92f7-d9d39894f432)

Details: headlamp 0.25.1 (latest), Ubuntu 24.04, installed using the Debian / Linux amd64 .deb file from the Github Release page.

I repeated the failed page with developer tools, I see in the console this error at `file:///opt/Headlamp/resources/frontend/assets/vendor-mui-C3ciNw1R.js:39`:

```
TypeError: Cannot read properties of undefined (reading 'status')
    at makePodStatusLabel (index-E81_fS_Z.js:1113:20828)
    at Object.render (index-E81_fS_Z.js:1113:22011)
    at st.Cell (index-E81_fS_Z.js:892:332322)
    at MRT_TableBodyCellValue (index-E81_fS_Z.js:892:220884)
    at Wf (vendor-mui-C3ciNw1R.js:37:52830)
    at Rb (vendor-mui-C3ciNw1R.js:41:8734)
    at $b (vendor-mui-C3ciNw1R.js:41:950)
    at nR (vendor-mui-C3ciNw1R.js:41:878)
    at Wi (vendor-mui-C3ciNw1R.js:41:730)
    at Rp (vendor-mui-C3ciNw1R.js:39:10827)
hp @ vendor-mui-C3ciNw1R.js:39
n.payload @ vendor-mui-C3ciNw1R.js:39
$a @ vendor-mui-C3ciNw1R.js:37
yh @ vendor-mui-C3ciNw1R.js:37
Rb @ vendor-mui-C3ciNw1R.js:41
$b @ vendor-mui-C3ciNw1R.js:41
nR @ vendor-mui-C3ciNw1R.js:41
Wi @ vendor-mui-C3ciNw1R.js:41
Rp @ vendor-mui-C3ciNw1R.js:39
(anonymous) @ vendor-mui-C3ciNw1R.js:37
e.unstable_runWithPriority @ vendor-mui-C3ciNw1R.js:26
Kr @ vendor-mui-C3ciNw1R.js:37
Xy @ vendor-mui-C3ciNw1R.js:37
bo @ vendor-mui-C3ciNw1R.js:37
ar @ vendor-mui-C3ciNw1R.js:39
Hf @ vendor-mui-C3ciNw1R.js:37
me @ index-E81_fS_Z.js:849
ue @ index-E81_fS_Z.js:849
Re @ index-E81_fS_Z.js:849
Se @ index-E81_fS_Z.js:849
ye @ index-E81_fS_Z.js:849
await in ye (async)
streamResultsForCluster @ index-E81_fS_Z.js:849
list @ index-E81_fS_Z.js:849
(anonymous) @ index-E81_fS_Z.js:849
(anonymous) @ index-E81_fS_Z.js:849
aR @ vendor-mui-C3ciNw1R.js:41
e.unstable_runWithPriority @ vendor-mui-C3ciNw1R.js:26
Kr @ vendor-mui-C3ciNw1R.js:37
yr @ vendor-mui-C3ciNw1R.js:41
Rp @ vendor-mui-C3ciNw1R.js:39
(anonymous) @ vendor-mui-C3ciNw1R.js:37
e.unstable_runWithPriority @ vendor-mui-C3ciNw1R.js:26
Kr @ vendor-mui-C3ciNw1R.js:37
Xy @ vendor-mui-C3ciNw1R.js:37
bo @ vendor-mui-C3ciNw1R.js:37
my @ vendor-mui-C3ciNw1R.js:41
Yw @ vendor-mui-C3ciNw1R.js:37
```

**Comment by sniok** [comment]
Thanks for a detailed bug report! I've opened a PR with a fix for this
