### ISSUE TITLE
"Jobs" section fails in EKS k8s v1.31

### ISSUE THREAD

**Issue by jliedy** [headlamp-k8s/headlamp#2446]
We recently upgraded one of our EKS clusters to v1.31 and now the "Jobs" section fails to load (the page "Uh-oh! Something went wrong." comes up).

As an aside, I found this out trying to troubleshoot why a bash script we use internally was having issues pulling the status type of a job using `kubectl get "job/job" -o jsonpath='{.status.conditions[0].type}'`
Initially, a completed job would output `Complete` at that tier, but later would only output `Complete` at the `.status.conditions[1].type` tier after the upgrade.

**Comment by jliedy** [comment]
Oh, I should probably say I'm running this on `Ubuntu 24.04.1 LTS` using the .deb package install (v0.25.1).

**Comment by jliedy** [comment]
It could be that `.status.conditions[*].type` would output both `SuccessCriteriaMet` and `Complete`

**Comment by jliedy** [comment]
@joaquimrocha Let me know if there's any info I can grab that would be helpful.

**Comment by illume** [comment]
Thanks for the report @jliedy 

This is the PR by @sniok that I think it was fixed in:
- https://github.com/headlamp-k8s/headlamp/pull/2395

(Should be in the next release in the next week or so)
