### ISSUE TITLE
Headlamp app is not moving minikube from stopped to started on home

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#2478]
## Describe the bug

- minikube is stopped
- headlamp app is started and is on the home screen showing minikube is stopped
- minikube is started
- headlamp app doesn't show minikube as started (you have to reload to see it started)

## To Reproduce
as above

## Environment (please provide info about your environment):
 - Installation type: WSL ubuntu 22
 - Headlamp Version: main branch with cd app; npm start

I'm not sure if it's a regression.

**Comment by skoeva** [comment]
I believe this extends to any changes with the clusters. Sometimes to solve this I end up needing to go to `./config/Headlamp` and clearing the local state and restarting the app

**Comment by sniok** [comment]
It doesn't seem to be related to any recent change. From what I can see it does react when clusters are added/removed but doesn't recheck the status/errors. Opened a PR with a fix
