### ISSUE TITLE
Contexts removed from kubeconfig is not updated

### ISSUE THREAD

**Issue by yolossn** [headlamp-k8s/headlamp#2541]
## Describe the bug
Headlamp watches for changes in the kubeconfigs to keep the contexts in sync with the ones in the kubeconfig files. When a context is added it is reflecting in the UI but when a cluster is removed it is still showing up.

## To Reproduce
Steps to reproduce the bug:
1. Start Headlamp
2. Add a new context to the kubeconfig file and refresh headlamp
3. The context shows up in the UI
4. Remove out a context from the kubeconfig file and refresh headlamp
5. The removed context still shows up in the UI

**Comment by knrt10** [comment]
I am able to reproduce this issue

**Comment by vyncent-t** [comment]
not sure if there was a step I missed but when adding another context and refreshing it errored out and didnt render any data for any of the normal resources

**Comment by vyncent-t** [comment]
I was able to get it to reload with this config

![image](https://github.com/user-attachments/assets/08c0ea59-da44-4c3e-bbdf-b6f1a59f168a)

**Comment by vyncent-t** [comment]
also I did not add another user or another cluster field, was able to get it to render and delete in the UI by doing just the context above
