### ISSUE TITLE
Sorting by duration incorrectly sorts seconds vs minutes

### ISSUE THREAD

**Issue by rukas** [headlamp-k8s/headlamp#2564]
## Describe the bug
When sorting jobs by duration the UI incorrectly sorts a larger number of seconds to be greater than a smaller number of minutes. 

Ex. 59s is larger than 19m

## To Reproduce
Steps to reproduce the bug:
1. Go to Jobs
2. Run jobs that run various durations, including some that run for seconds and some that run for minutes
3. Sort by Duration (either ascending or descending)
4. See that it is incorrectly sorting the duration

## Environment (please provide info about your environment):
 - Installation type: Windows
 - Headlamp Version: 0.26.0
 - Other: n/a

## Are you able to fix this issue?
No.
> Do you want to help fix this issue? Please see our [contribution docs](https://headlamp.dev/docs/latest/contributing). For any non-trivial contributions, we advise you to join our [our slack channel](https://kubernetes.slack.com/messages/headlamp) to discuss the implementation with Headlamp's core developers.

## Additional Context
![image](https://github.com/user-attachments/assets/1530e73d-f370-48e2-bb61-c7b44df366a0)

**Comment by skoeva** [comment]
Thanks for submitting this, will take a look
