### ISSUE TITLE
Auth failed dialog has no option to go home when there's only 1 cluster

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#2591]
## Describe the bug

This is a reminiscence of when we didn't show the home if only one cluster was configured (because there's not much sense for pure in-cluster deployments): the auth dialog is not showing an option to go back home if there's only one cluster configured.

## To Reproduce
Steps to reproduce the bug:
1. Have only one cluster configured for Headlamp; make sure the cluster is unnaccessible.
2. Open Headlamp try to access that cluster -> it should bring you to the auth failed dialog and there's no option to go back to the home view

## Environment (please provide info about your environment):
 - Installation type: any
 - Headlamp Version: 0.26.0

**Comment by skoeva** [comment]
@joaquimrocha when this happens, we can just navigate to home using the alert at the top (assuming it shows up):

![image](https://github.com/user-attachments/assets/9cbe4c9d-e404-41d1-b20a-698bd975be92)

but if it doesn't, we can have the back button persist as shown to navigate to home. maybe the notification can be more descriptive though
