### ISSUE TITLE
Application install failed due to Error creating release request Error: Bad request

### ISSUE THREAD

**Issue by susanshi** [headlamp-k8s/headlamp#2618]
## Describe the bug
I would like to install a new application on my aks cluster using the application UI.

Expected:
Application should be installed successfully.
If I did see an error msg, error log or trouble shooting guide should be easy to find.
Actual:

![image](https://github.com/user-attachments/assets/ef217a15-78f0-436a-8e78-72a2ec153ad6)

## To Reproduce
Steps to reproduce the bug:
1. Connect to my aks cluster
2. Validated other UI works. e.g. i can view configMap/Crd/Secrets on my cluster
3. Go to apps
4. I tried to install Trivy Operator  ( also tried to install other app, same error)
5. fill out the release name , using default namespace
6. click on install

Error:
Error creating release request Error: Bad request

## Environment (please provide info about your environment):
 - Installation type: Windows winget
 - Headlamp Version: v1.30.6
 - Other: aks cluster

## Are you able to fix this issue?
No
I would like to see a TSG section on the doc website, happy to contribute to that if that exist.

**Comment by joaquimrocha** [comment]
Hi @susanshi ! I am puzzled by this one. Is this problem persisting? You can also check the dev tools (browser or app) and see if there's some related error there we can pursue.

**Comment by joaquimrocha** [comment]
I confirm the issue and have created a fix for it. To be released later today.
