### ISSUE TITLE
"Load Cluster" results in no added clusters

### ISSUE THREAD

**Issue by himslm01** [headlamp-k8s/headlamp#2622]
## Describe the bug
First install of the Flatpack on OpenSuse Tumbleweed.
I'm trying to add clusters to connect to.
But having used the "Load Cluster" workflow, no clusters are available.

## To Reproduce
Steps to reproduce the bug:

- Using the "Load Cluster" option, select the kubeconfig file I want to add the clusters from.
- I see the clusters listed in the "select clusters" dialogue. They are all selected.
- I press 'Next" and "Clusters successfully set up!" is displayed.
- I press "Finish" and no clusters are listed.

## Environment (please provide info about your environment):
- OpenSuse Tumbleweed Linux 
- Headlamp stable branch from installed Flatpack

## Are you able to fix this issue?
Not immediately

## Additional Context
Console log - if it's of any use.
[headlamp_console.log](https://github.com/user-attachments/files/17965768/headlamp_console.log)

**Comment by agrevtsev** [comment]
Same on macOS, arm64, Headlamp Version 0.26.0 installed from homebrew.

**Comment by joaquimrocha** [comment]
cc/ @knrt10

**Comment by knrt10** [comment]
Looking into this

**Comment by knrt10** [comment]
I can reproduce this, fixing it

**Comment by knrt10** [comment]
@himslm01 it is fixed now in current main, can you please test it?

`cd app && npm i && npm start`

**Comment by himslm01** [comment]
Thanks @knrt10.
> `cd app && npm i && npm start`

I can't get Headlamp app to work in a VSCode Devcontainer, so I'll need to wait until there is a release.

**Comment by himslm01** [comment]
I have installed the most recent Flatpack, 0.28.0. I get the same result, no clusters are listed after I import a valid kube config file.

Do you need more logs?

It is a shame that I have to import the kube config files at all. They are referenced in my KUBECONFIG env variable. I guess it's something to do with the Flatpack security model.

I am surprised that not even the one cluster in my `~/.kube/config` file is listed by default in Headlamp.

If there's any other help I can give to solve this problem then please ask :⁠-⁠)

**Comment by himslm01** [comment]
A fix for this issue is to make Flatpack be allowed to read from a user's `.kube` folder, negating the need to import cluster definitions.

`sudo flatpak override io.kinvolk.Headlamp --filesystem=$HOME/.kube`

Alternatively, use the Appimage, which doesn't have the security sandbox that Flatpack has and can read the `.kube` directory without any faffing about.
