### ISSUE TITLE
Documentation for installing plugins via Helm chart

### ISSUE THREAD

**Issue by slitsevych** [headlamp-k8s/headlamp#2628]
Greetings! 
I have a question regarding any guide or instructions (if any) on how to install custom plugins (e.g. Opencost) for in-cluster Helm installation. 
I've looked through issues/documentation but was not able to find any hints, apparently this has something to do with initContainers/PVC but is there a clear and concise instruction of doing that? 

Would appreciate any feedback.

**Comment by joaquimrocha** [comment]
@slitsevych , we have a couple of guides but it's true we should have a more direct access in the docs.
Here is what we have:
https://headlamp.dev/blog/2022/10/20/best-practices-for-deploying-headlamp-with-plugins
https://github.com/headlamp-k8s/plugins/tree/main/flux#readme (for Flux but you can create a container image with the OpenCost plugin)

**Comment by slitsevych** [comment]
@joaquimrocha Oh, thanks a lot, that will do it for now, will try to build an image and inject plugins with the help of it... may I also clarify real quick, is there a list of plugins that are compatible with in-cluster deployment? I presume that some of the plugins are only for Desktop, right?

**Comment by joaquimrocha** [comment]
You are right. If you are looking for such plugins, check out those on ArtifactHub that have the "in-cluster" under Headlamp Flavors.

**Comment by slitsevych** [comment]
@joaquimrocha gotcha, many thanks!
