### ISSUE TITLE
Navigating to Network Policies via Tabs goes to Port Forwards

### ISSUE THREAD

**Issue by sniok** [headlamp-k8s/headlamp#2663]
Steps to reproduce the bug:

1. go to network, collapse sidebar to get tabs
![image](https://github.com/user-attachments/assets/90f283b4-7159-4477-b662-f6b05b65da3d)
2. click on "Network Policies", notice page not found error and /portforwards URL
![image](https://github.com/user-attachments/assets/6ca892c0-d8c3-4ba4-b4c8-136c90b50163)

**Environment** Web version

**Are you able to fix this issue?** maybe unless someone else wants to take a look at this

**Comment by skoeva** [comment]
might just be a routing logic error, can take a look
