### ISSUE TITLE
Plugin Settings switch buttons not changing

### ISSUE THREAD

**Issue by vyncent-t** [headlamp-k8s/headlamp#2666]
## Describe the bug

When in app mode and changing the setting of a plugin enable/disable the switches do not display the correct positioning. They always remains in the same position the page was loaded on whenever changing, the UI will update to the correct enable / disable positions when the save button is clicked and the page reloads. This seems to be a UI only issue as the save button still continues to enable / disable plugins on reload.

![image](https://github.com/user-attachments/assets/b3b27e4a-81ed-4cd6-b944-34c99931e70d)

## To Reproduce
Steps to reproduce the bug:
1. Open headlamp in app mode and navigate to settings then plugins settings page
2. Have a plugin installed and click on the enable switch
3. Observe that the status does change but the button does not

## Are you able to fix this issue?
Looking into this now

**Comment by joaquimrocha** [comment]
Fixed
