### ISSUE TITLE
Table select all from partial not working as expected

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#2669]
## Describe the bug

In a table, if you select a couple of rows and then click the `-` (select/deselect all) button, you'll see that it selects all rows but doesn't turn into a checkmark nor does it do anything when clicked again.

## To Reproduce
Steps to reproduce the bug:
1. In the main branch, go to pods + select 2 pods
2. Click the `-` on the top check mark (checkmark column) -> all rows are selected 
3. Click the `-` again -> nothing happens

I expected the `-` checkbox to deselect the 2 selected rows on step 2 instead.

## Environment (please provide info about your environment):
 - Installation type: any
 - Headlamp Version: main

**Comment by skoeva** [comment]
Played around with the tables in the [MRT docs](https://www.material-react-table.com/docs/guides/row-selection) as well as in Headlamp, seems like the functionality is working as intended
