### ISSUE TITLE
Hiding columns in tables in plugins breaks layout 

### ISSUE THREAD

**Issue by mgalesloot** [headlamp-k8s/headlamp#2676]
## Describe the bug
Hiding columns in tables in plugins breaks layout 

## To Reproduce
Steps to reproduce the bug:
1. Open Flux/Kustomizations  
2. Hide the column Last Updated
3. Note there is a new colum to the right 'apps'

This happens in all table views of Flux and Kubescape so I believe it is a generic issue in the Headlamp libs. The issue does NOT happen with the HeadLamp core views such as deployments, nodes, etc.

![image](https://github.com/user-attachments/assets/cae399b1-1640-4134-9d07-c667b7ec65e0)

## Environment 
Headlamp v25 or later 

## Are you able to fix this issue?
No

**Comment by sniok** [comment]
Thanks for opening an issue! I've opened a PR with a fix for this.
