### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#278]
## Current situation

The release process requires following a recipe doc with several steps.

## Impact

We need to fully follow stuff like renaming packages, etc. which can leads to errors and takes time.

## Ideal future situation

Some of the steps should be automated so things become quicker and less error prone.

**Comment by illume** [comment]
There's always things related to releases we need to automate or fix. We have a release label now.

So, I think we can close this old issue and use the release label.
