### ISSUE TITLE
oidc login does not respect base uri

### ISSUE THREAD

**Issue by mhaddon** [headlamp-k8s/headlamp#292]
If you run headlamp on a server, and configure both the oidc login and base uri, then when you go to login the authentication popup is not respecting the configured base uri.

**Comment by joaquimrocha** [comment]
Hi @mhaddon , we (assumed we) have fixed this issue in #238 which went out in version 0.4.0. Can you confirm you're running that version?
Once it's confirmed we'll look into the issue.

Thanks in advance.

**Comment by mhaddon** [comment]
It still seems to be an issue.

I am using 0.4.0.

**Comment by joaquimrocha** [comment]
Thanks for confirming. We'll look into it, @mhaddon .

**Comment by illume** [comment]
Fixed in:
- #1158
