### ISSUE TITLE
Build & publish ARM container images

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#369]
## Current situation

We do publish ARM versions of the Headlamp app, but we don't have an ARM version for the container image.

## Impact

Users who want to deploy Headlamp in an ARM cluster, cannot do it.

## Ideal future situation

We have the Headlamp ARM images published to the registry as well.

**Comment by vielmetti** [comment]
Sounds like a good idea, I would try this out.

Current setup is Apple Silicon + Rancher Desktop + arm64. The provided Apple Silicon standalone app seems to work fine.

**Comment by mazzy89** [comment]
I've backed an updated for my homelab k3s clusters. Running w/o any issues on my RPI 4 cluster. here available https://hub.docker.com/repository/docker/mazzy/headlamp/tags?page=1&ordering=last_updated

**Comment by illume** [comment]
Re-opening until the images are published.

**Comment by joaquimrocha** [comment]
Images are published. Let's close it.
