### ISSUE TITLE
[RFE] Add support to view and manage helm releases 

### ISSUE THREAD

**Issue by yolossn** [headlamp-k8s/headlamp#533]
Helm is a widely used kubernetes package manager, having a way to manage helm releases will be a good idea. Maybe we can create this as a plugin for headlamp.

**Comment by joaquimrocha** [comment]
Should this be a plugin or a core feature?
More importantly, does it make sense to be enabled on in-cluster? I think you had mentioned that this would need the helm binary, meaning it'd likely be a desktop-only feature.

**Comment by illume** [comment]
@yolossn Is this about providing a UI for all the helm commands or did you have subset in mind?

List would be useful at minimum IMHO. A slightly larger feature set could be taken from the CKAD exam, where they have a set of commands people should know how to use.

For browsing charts, that's basically the feature set of https://artifacthub.io/  / https://github.com/artifacthub/hub Which includes browsing, filtering and such. I can imagine people also wanting to add other (perhaps internal) chart repos.
> [Artifact Hub](https://artifacthub.io/) is a web-based application that enables finding, installing, and publishing packages and configurations for CNCF projects.

We could link out to Artifact Hub to cover the discovery feature set perhaps?

> More importantly, does it make sense to be enabled on in-cluster? I think you had mentioned that this would need the helm binary, meaning it'd likely be a desktop-only feature.

Does it make sense in-cluster? To use Headlamp to explore a cluster that uses Helm, it would be useful to see what helm things are installed there IMHO. Probably you could see this information already in a cumbersome way by exploring config maps(where helm stores its state). Apart from the binary we could run this in-cluster via either the helm Go SDK or by including the helm binary inside our image (or in a separate image) running on the cluster.

@yolossn I was wondering how Flux/Argos fits in here?
https://helm.sh/blog/tools-to-manage-helm-declaratively/

**Comment by yolossn** [comment]
@illume @joaquimrocha sorry for the late reply.

> Is this about providing a UI for all the helm commands or did you have subset in mind?
Yes it is about providing a UI for helm, Listing some of the commands at the top of my mind below:
- List charts (From artifacthub or other sources)
- Install charts 
- List Releases
- Upgrade a Release
- Delete a Release
- Update the values with which a Release was made

> Does it make sense in-cluster?
> Should this be a plugin or a core feature?

Like @illume pointed out it is possible to be both an in-cluster feature and an app only feature. It depends on if we prioritize to bundle this feature always with headlamp or make it optional. If we want this to be optional then we have to take the app only route if we want it to be a core feature we can explore using the Helm Go SDK.

>I was wondering how Flux/Argos fits in here?

I have limited experience with Flux/Argos but from my first glance I think this expects the cluster to have Argo CI/CD or Flux installed in the cluster which we don't have control over. Maybe we can check if the cluster has Flux/Argo and enable the declarative features selectively. That being said I am not sure about how widely this declarative helm concept is used.

**Comment by Smana** [comment]
@joaquimrocha Hello, sorry but I don't understand what you mean by "this is done"? Actually I'm looking for a web UI to use with Flux. As you may know this is one of its drawback compared to ArgoCD. An existing web UI named weave-gitops won't be maintained and a specific one is under development named capacitor. That said, I think that'd be great to have basic operations on flux resources in Headlamp.

**Comment by yolossn** [comment]
Hey @Smana We have `app-catalog` [plugin](https://github.com/headlamp-k8s/plugins) to view and manage Helm charts, but it is available only in the desktop version of Headlamp.
