### ISSUE TITLE
[RFE] test setup for plugins

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#569]
## Current situation

Currently there is no test setup for plugins, so people have to do it themselves.

## Impact

For people wanting to write tests it's easier if it's setup and working.

## Ideal future situation

`npm run test` for plugins works.

## Implementation options

Like with the tools create react app supplies.

- jest
- react testing library

Storybook is kind of related, maybe worth considering at the same time.

**Comment by illume** [comment]
Probably need a copy of Headlamp frontend/ code for this. 
(Either copied into headlamp-plugin or via a headlamp package.)

Because the tests run the code and therefore just supplying types are not sufficient.

**Comment by joaquimrocha** [comment]
This is done.
