### ISSUE TITLE
[RFE] end-to-end (e2e) tests

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#570]
## Current situation

We don't have any end-to-end tests for Headlamp.

## Impact

We are not as confident as we could be that different versions of the Headlamp (app, web) work.

## Ideal future situation

There are some basic end-to-end tests.

- [x] setup a cluster (minikube probably)
- [x] deploy headlamp image https://github.com/kinvolk/headlamp/pull/647
- [ ] run browser-based tests against it
    - log in, and check if the pods are listed
- [ ] plugin e2e tests, example plugin should include e2e tests that can run against a Headlamp

## Implementation options

- minikube has documentation on using minikube on CI with github actions. https://minikube.sigs.k8s.io/docs/tutorials/setup_minikube_in_github_actions/
- testing library has documentation on using testing library with the cypress e2e. https://testing-library.com/docs/cypress-testing-library/intro/
- cypress has docs on using it with github actions: https://docs.cypress.io/guides/continuous-integration/github-actions
- Electron react boilerplate has docs on writing e2e tests, so the app can be tested as well as the container image https://electron-react-boilerplate.js.org/docs/e2e-tests/

**Comment by knrt10** [comment]
closing this issue since we now have streamlined setup for e2e tests. Thank you @illume for the groundwork on this.
