### ISSUE TITLE
[RFE] Add accessible namespaces option

### ISSUE THREAD

**Issue by blobor** [headlamp-k8s/headlamp#679]
## Current situation

If a user doesn't have permission to list namespaces but only has access to specific namespaces, he basically can't use Headlamp.

## Ideal future situation

Headlamp could add an option for predefining "accessible namespaces" for a user via parameters (like env variables) or user/cluster settings (via user input before login).

![image](https://user-images.githubusercontent.com/4813007/186126895-2927122a-c89a-4500-b3cc-044c7395b2b8.png)

## Additional information

Similar behavior has a `Lens` tool.
![image](https://user-images.githubusercontent.com/4813007/186122993-95e96f4b-44a7-47f1-a24e-085446294613.png)

**Comment by joaquimrocha** [comment]
Thanks! This makes a lot of sense and we are planning on having a settings view in the next release if it all goes well (not sure if we can squeeze this feature in, but it'd be nice).
It should also be set per cluster AFAIU, so we can have clusters with different permissions settings set up.

**Comment by joaquimrocha** [comment]
This depends on #16 .

**Comment by joaquimrocha** [comment]
Not making it to v0.13.0 yet. Let's plan it for later.

**Comment by callmevladik** [comment]
@joaquimrocha any details when it is planned for? 🙂

**Comment by callmevladik** [comment]
@joaquimrocha bump :)

**Comment by joaquimrocha** [comment]
This depending on the settings panel, which is dependent on the notifications view.
We're aiming to have it in 0.14.0 but still have a few things in the pipeline before that.

**Comment by ashu8912** [comment]
I Can pick this one
