### ISSUE TITLE
[RFE] Allow plugins to remove resource detail header actions

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#710]
## Current situation

Plugins can add header actions (to be displayed for te resources' details views) but they cannot remove or clear them.

## Impact

This limits how plugin developers can tweak this part of the UX.

## Ideal future situation

Plugins can either remove all header actions or particular ones.

## Implementation options

Ideally, plugins would be able to provide a function that receives a list of identifiable header actions, and is supposed to return another list. This would allow the plugins to remove certain actions, condition the removal on certain factors, reshuffle their position, also add new ones, etc.

**Comment by joaquimrocha** [comment]
@lijianzhi01 , FYI this is the issue tracking the header actions.

**Comment by illume** [comment]
Example plugin showing how to remove the delete button:
```ts
// This example shows how to remove DeleteButtons from the detail view action button lists.
import { DeleteButton } from '.../resources/DeleteButton';

function removeDeleteButton = (actions, isAction) => {
 return headerActions.filter((action) => !isAction(action, DeleteButton))
}
registerDetailsViewHeaderActionFilter(removeDeleteButton)
```

---

Here's an implementation of isAction that works with react instances, and the functions. It doesn't use the name property because that can be mangled in minification.

```ts
function isAction(action, type) {
  return action === action || action?.type === type;
}
```

The function with types:
```ts
function isAction(action: HeaderActionType, type: ((...args: any[]) => JSX.Element)) {
  return action === action || action?.type === type;
}
```

For reference:

```ts
export type HeaderActionType = ((...args: any[]) => JSX.Element | null) | null | ReactElement;
```
- ReactElements have a type property. https://beta.reactjs.org/reference/react/createElement

**Comment by illume** [comment]
Because we spoke that filters should probably look the same and be consistent in different places...

Example plugin showing how to remove the delete button:
```ts
// This example shows how to remove DeleteButtons from the detail view action button lists.
import { DeleteButton } from '.../resources/DeleteButton';

function removeDeleteButton = (items, isItem) => {
 return items.filter((action) => !isItem(item, DeleteButton))
}
registerDetailsViewHeaderActionFilter(removeDeleteButton)
```

**Comment by joaquimrocha** [comment]
My concern with this approach is that, besides the slight quirkiness of being passed a function to compare a component, is that we're identifying which component it is, rather than their role (which is usually what I'd guess plugin developers want). i.e. if a plugin replaces the delete button with their own delete button and wants that to be interpreted further as the new delete, this approach will make that very difficult.

Other issues with comparing the component is e.g. if we keep the `DeleteButton` around in the same location but start using a new `HeaderActionDeleteButton` exported as a different name, this would break the comparison for plugins.

Do these concerns make sense?

Essentially, we should be able to let devs know a bit more semantically what's the role/purpose of each action, to solve something like: "As a plugin developer, I want to remove whatever is identified as a 'XYZ' button, even if it's been previously overridden by another plugin".

What if we define the items list as objects of type:
```typescript
  LabeledHeaderAction {
    id: string;
    action: ((...args: any[]) => JSX.Element | null) | null | ReactElement;
  }
```

This way, devs could quickly check `labeledAction.id === 'delete'` (or with an enum `DELETE_HEADER_ACTION_ID = 'delete'`).
This suggests that devs would need to add actions also with a label, and we've not been requiring this, but maybe we can still support label-less actions by computing whatever id from a plugin's ID (computed from the file name or random till we have things like a manifest)...

WDYT? Any concerns about this I am not contemplating?

**Comment by illume** [comment]
I don't like the added overhead of string names, when we have named types already. Especially when filters don't appear to be a common use case based on functionality used and requested so far. This way the more commonly used functionality does not require adding a duplicate string name in addition to the component name that's there already.

An `isItem` function encapsulates the equality comparison so internals do not necessarily need to be understood, and can be changed later if needed. As can be seen in the removeDeleteButton example, it's not really complicated to use. Perhaps less complicated than having to know object internals.

**Comment by joaquimrocha** [comment]
> I don't like the added overhead of string names, when we have named types already. Using types gives the advantage of the type checker being able to be used to check them.

That's the thing. You don't have named types. Types get minimized, so you have component comparison and you cannot import components from other plugins in order to compare, so this is limited to the default components semantics, besides the problem I mentioned with breaking plugins if we change the name of the components being used there.

> An isItem function encapsulates the equality comparison so internals do not necessarily need to be understood, and can be changed later if needed. As can be seen in the removeDeleteButton example, it's not really complicated to use. Perhaps less complicated than having to know object internals.

Devs still have to know what components are being used by default and keep up to date on where to import them from. This can only be understood by comprehensive and continuously updated docs, whereas knowing that actions have a label + component seems easier in my understanding.

As an iteration on the comparison function, maybe we could make it about getting the components role, and have a list of roles available.
```typescript
import {ActionRoles} from '@kinvolk/headlamp-plugin/lib...'

function removeDeleteButton = (items, getRole) => {
 return items.filter((item) => getRole(item) !== ActionRoles.DELETE);
}
```

By default the `getRole` could return `UNKNOWN` but I am sensing we'd be requested a way to set up a role for actions.
I'm not sure this is a big improvement over having the association as objects, but it seems to solve most of the concerns I wrote.

WDYT?

**Comment by illume** [comment]
> You don't have named types.

The types are named. It doesn't matter about minimization, because relying on object internals is a bad idea anyway.

> This can only be understood by comprehensive and continuously updated docs

As well as by looking at the component in the browser, or by tab completing on imports. And docs, which as well as a list, could mention how to find other buttons. (If they know to look for a .type attribute in the items given, they could use that too.)

> ActionRoles

I guess this would be more to maintain compared to using the object and an isItem.

> you cannot import components from other plugins in order to compare

There's not a requirement from a request for interfering with other plugins (unless I'm mistaken). Because there's not an identified need from a request I don't think it's worth considering further. Although it would be possible to address, because the filter just needs access to the object.

**Comment by joaquimrocha** [comment]
> > You don't have named types.
> 
> The types are named. It doesn't matter about minimization, because relying on object internals is a bad idea anyway.
>
> > This can only be understood by comprehensive and continuously updated docs
> 
> As well as by looking at the component in the browser, or by tab completing on imports. And docs, which as well as a list, could mention how to find other buttons. (If they know to look for a .type attribute in the items given, they could use that too.)

You're relying on internals as well since you're important a component that you've realized it's being used internally and thus have to check if it will be supported in the future, in my understanding.

What I mean is that if you need to import the component in order to compare it, then we'd have to make sure that that's well explained and it's a higher burden on maintenance to keep the components unnamed or unwrapped by some other components. All of this seems like relying on implicit behavior + documentation which is a riskier for both parties.
 
> > ActionRoles
> 
> I guess this would be more to maintain compared to using the object and an isItem.

My answer above this quoted paragraph has my argument for why I think this is not a higher maintenance burden (on the contrary).

> > you cannot import components from other plugins in order to compare
> 
> There's not a requirement from a request for interfering with other plugins (unless I'm mistaken). Because there's not an identified need from a request I don't think it's worth considering further. Although it would be possible to address, because the filter just needs access to the object.

It's true there is no requirement, but my point was more that if your plugin promises the user that it will remove whatever the delete button is, this promise is void if there's another plugin that just slightly replaces the delete component or wraps it around a confirmation dialog component for example.

**Comment by joaquimrocha** [comment]
This is available in main now.
