### ISSUE TITLE
[RFE] spawn job from cronjob via button

### ISSUE THREAD

**Issue by scones** [headlamp-k8s/headlamp#787]
## Current situation

Currently i can look at a cronjob, but not force start it.

## Impact

For the few people that prefer an UI, but need to restart a cronjob after an update or similar, they can't with this UI.

## Ideal future situation

add a button to create a job from a cronjob. basically the pendant to
`k create job --from=cronjob/some-cron some-cron-manual-001`

## Implementation options

see above

## Additional information

-

**Comment by joaquimrocha** [comment]
This makes sense. We'll look into it.

**Comment by joaquimrocha** [comment]
Fixed. #938
