### ISSUE TITLE
Allow to apply v1/List "resources"

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#805]
## Description

Users may want to apply lists of resources in the form of a v1/List kind but this is not a regular resource in K8s. See https://github.com/kubernetes/kubectl/issues/837 .

Here is an example of such list: https://kubernetes.io/docs/concepts/policy/resource-quotas/#resource-quota-per-priorityclass

## Impact

Headlamp doesn't allow this kind of list to be applied as its expecting only regular resources (with a kind and a metadata.name).
Moreover, the resources defined in the list will not get the namespace automatically added since we're checking for a regular resource.

## Expected behavior

Headlamp allows to apply `List` kind objects, and adds the default namespace to any resources in the list that need it.

**Comment by siddhant1** [comment]
I can pick this up!

**Comment by joaquimrocha** [comment]
The #809 is merged now. @siddhant1 , do you still want to work on this?

**Comment by sidUdaan** [comment]
Will start tomorrow, @joaquimrocha

**Comment by siddhant1** [comment]
Yes, can you pass me the setup instructions @joaquimrocha

**Comment by ashu8912** [comment]
This is fixed now with #909
