### ISSUE TITLE
[RFE] support docker-compose files

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#812]
## Current situation

Would be nice to be able to support docker-compose files, since some folks like using those.

## Impact

People used to docker-compose might prefer that.

## Ideal future situation

People could use docker compose files if they prefer.

## Implementation options

The kubernetes docs have a section on this: https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/

Where they recommend using the https://kompose.io/ tool.

**Comment by ashu8912** [comment]
This looks interesting to me, i can pick this one :D, would be a good learning opportunity

**Comment by illume** [comment]
We have a kompose plugin published now, so I'm going to close this. https://github.com/headlamp-k8s/plugins/tree/main/kompose

If there is future work for that plugin, that can be tracked elsewhere. At time of writing there are no open issues I can find for it.
