### ISSUE TITLE
[RFE] Add header action to stop/start CronJobs

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#896]
## Current situation

Similar/related to #787 , we should add an option to pause/resume CronJobs.

This makes it very simple for operators to pause/resume which is useful for debug purposes as well.

## Implementation options

A header action seems like the right place to have this.

**Comment by ashu8912** [comment]
I can take this one

**Comment by ashu8912** [comment]
fixed in #974 #938
