### ISSUE TITLE
Documenting "backend" functions and data structures with "doc comments"

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#930]
Parts of `headlamp_backend` are undocumented. The benefits are better quality (less bugs) and it makes code easier to understand.

See:
- [Go Doc Comments](https://go.dev/doc/comment) for how to add doc comments in golang.
- [backend/cmd](https://github.com/headlamp-k8s/headlamp/tree/main/backend/cmd) and [backend/pkg](https://github.com/headlamp-k8s/headlamp/tree/main/backend/pkg) folders

## A list of some functions and data structures that need documenting

- [ ] kubeconfig.go@GetContextsFromKubeConfigFile
- [ ] headlamp.go@PortForward
- [ ] headlamp.go@PortForwardPayload
- [ ] headlamp.go@contextProxy
- [ ] headlamp.go@stopOrDeletePortForward
- [ ] plugins.go@addPluginRoutes
- [ ] plugins.go@pluginURLsForDir

There are more functions and fields than is represented in the list above. Feel free to add or improve docs for other functions. Additionally, some of the existing comments could be improved.

**Comment by jingchu000** [comment]
hey @illume . Could you pls assign it to me?

**Comment by illume** [comment]
I’ve assigned you. Let me know if you have any questions?. We’re also on the kubernetes slack in the headlamp channel if you want to chat about it.

**Comment by jingchu000** [comment]
@illume ， Can you help me review? Thanks
