### ISSUE TITLE
Align the calendar and date wherever used

### ISSUE THREAD

**Issue by ashu8912** [headlamp-k8s/headlamp#958]
If you go to a timestamp that uses the date and calendar option to show a date you will see that the date and calendar are not properly aligned
<img width="161" alt="Screenshot 2023-02-15 at 2 26 38 PM" src="https://user-images.githubusercontent.com/30126128/218982950-2391e3a5-1a26-4989-9d4a-d66abe121146.png">

The date and calendar should be correctly center aligned.

**Comment by thiyagarajan17** [comment]
Could you assign me for the fix.. would love to work on it

**Comment by joaquimrocha** [comment]
@thiyagarajan17 , this is already assigned to a member of our team.
We'd be very happy if you can work on another task. Let us know if there's anything not assigned that you would like to work on.

**Comment by joaquimrocha** [comment]
@thiyagarajan17 , we couldn't yet pick this issue up after all. We're happy to have you do it if you want, and we're here to help.

**Comment by egomezbpedro** [comment]
Hi team, 

Could this perhaps be done in the [Label](https://github.com/headlamp-k8s/headlamp/blob/main/frontend/src/components/common/Label.tsx) file by modifying the following:
``` diff
const useHoverInfoLabelStyles = makeStyles({
  display: {
-    display: 'inline-block',
+   display: 'flex',
+   alignItems: 'center',
+   justifyContent: 'flex-end'
  },
  noWrap: {
    whiteSpace: 'nowrap',
  },
  icon: {
    marginRight: '0.2rem',
    marginLeft: '0.2rem',
  },
});
```

Is also possible to use a child or possibly a sibling selector while keeping the inline-block as in:
``` diff
const useHoverInfoLabelStyles = makeStyles({
  display: {
      display: 'inline-block',
+   "& *": {
+      verticalAlign: 'middle'
+    },
  },
  noWrap: {
    whiteSpace: 'nowrap',
  },
  icon: {
    marginRight: '0.2rem',
    marginLeft: '0.2rem',
  },
});
```

Please let me know any feedback or other workaround suggestion or for this.

Thanks, Happy Friday :)

**Comment by egomezbpedro** [comment]
Even so the text and the icon seems not quite centred.
<img width="65" alt="Screenshot 2023-08-18 at 12 46 32" src="https://github.com/headlamp-k8s/headlamp/assets/57415533/8343d0e2-a273-421a-9677-9d1e54f0de3d">

**Comment by illume** [comment]
This issue was fixed. Thanks @egomezbpedro @vyncent-t
