### ISSUE TITLE
Fix the calendar icon color on dark theme

### ISSUE THREAD

**Issue by ashu8912** [headlamp-k8s/headlamp#986]
In some of the places, the color of the calendar icon is still dark instead it should be white as shown below
How it is:
<img width="18" alt="Screenshot 2023-02-28 at 11 30 55 AM" src="https://user-images.githubusercontent.com/30126128/221767510-5a850dfe-aeab-471c-babd-22b8dcec87d5.png">
How it should be
<img width="26" alt="Screenshot 2023-02-28 at 11 30 41 AM" src="https://user-images.githubusercontent.com/30126128/221767527-e4f0b726-0b5d-4b72-ac1a-5fd5c61ab8e0.png">

**Comment by xdevore** [comment]
Hello! I'm new to open source, but would love to try take on this bug if possible. If that would be alright, do you have any tips for potential solutions or getting started? Thanks :)

**Comment by egomezbpedro** [comment]
Hi @ashu8912,

I've been searching through the frontend codebase for a possible explanation for this issue, but I've not found anything. I'm still getting familiar with the code. I first thought to be a misbehaviour of the theme library but so far is been a dead end. 

I'll appreciate any insights that you may have on where to look for this behavior. 

Cheers

![Dark Theme Wrong](https://github.com/headlamp-k8s/headlamp/assets/57415533/f87ec522-34b0-44b6-b517-6e314d9a7378)
Dark Theme Correct
![Dark Theme Correct](https://github.com/headlamp-k8s/headlamp/assets/57415533/3fe3d57b-2bc8-45c4-8398-f3340ce9d135)
Light Theme Correct
![Light Theme Correct](https://github.com/headlamp-k8s/headlamp/assets/57415533/69932b33-fe8b-42c0-b096-5e47ea0b59b1)
Light Theme Wrong
![Light Theme Wrong](https://github.com/headlamp-k8s/headlamp/assets/57415533/1be3f7b9-2861-4df7-8d6c-07b030b1d075)

**Comment by ashu8912** [comment]
Hello @egomezbpedro first of all welcome to headlamp codebase :D,
Ok so about the issue It's an issue that is there in only some views like if you go to the namespace list view the calendar icon contrast there is not correct in dark theme and then the detail view for it also has the same issue, 
So this issue can be solved in two parts where we first find all the places where this is happening and then adding a pr that fixes this.

If you need any help with this i am more than happy to help.

**Comment by egomezbpedro** [comment]
Hi @ashu8912,

thanks for your inputs. What I've seen is that in the [Labels](https://github.com/headlamp-k8s/headlamp/blob/5057117bed114069ffc191af6a24c94d3df2f220/frontend/src/components/common/Label.tsx#L162C7-L162C30) file there are a set of classes that are being applied. In here what it can be done to normalize this behavior in all pages is to target the svg and force the correct color.

``` diff
const useHoverInfoLabelStyles = makeStyles({
  display: {
      display: 'inline-block',
+    '& svg': {
+     color: 'unset !important'
+  }
  },
```

I'm sure that there is another workaround to this same goal, please let me know your feedback on this and any other hints or tips on what to think for this change.

Thanks :)

**Comment by egomezbpedro** [comment]
Hi @ashu8912, 

Following the work done in #1359 we can close this issue.

Thank you
